/* loom_engine - C ABI for the Loom Engine deterministic core (Unity/C#, Godot, Go, C). One Rust core, byte-identical across every surface. */

#ifndef LOOM_ENGINE_H
#define LOOM_ENGINE_H

#pragma once

/* GENERATED by cbindgen - do not edit. Regenerate: cbindgen --config cbindgen.toml --crate loom_c_abi --output loom_engine.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Band codes (closeness ascending). Mirror loom_combat::range_bands.
 */
#define LOOM_BAND_ENGAGED 0

#define LOOM_BAND_NEAR 1

#define LOOM_BAND_FAR 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Library version as a borrowed, NUL-terminated static C string (never freed).
 */
const char *loom_version(void);

/**
 * Distance (feet) -> band code. Negative/uncomputable -> NEAR, like the core.
 */
int loom_band_from_distance_ft(int64_t feet);

/**
 * 1 iff `band` is at least as close as `max_band`; 0 otherwise / on a bad code.
 */
int loom_band_within(int band, int max_band);

/**
 * Deterministic single die [1, sides] from a fresh seed.
 */
uint32_t loom_roll_die(uint64_t seed, uint32_t sides);

/**
 * Deterministic sum of `count` dice of `sides` faces from a fresh seed.
 */
uint64_t loom_roll_dice(uint64_t seed, uint32_t count, uint32_t sides);

/**
 * Next raw u32 from a seeded PCG32 (for parity checks).
 */
uint32_t loom_pcg32_next(uint64_t seed);

/**
 * Python-floor division into `*out`. Returns 0 on success, -1 on a null out,
 * division by zero, or the i64::MIN / -1 overflow (true result 2^63 is not
 * representable in i64).
 *
 * # Safety
 * `out` must be a valid, writable `*mut i64` (or null, which returns -1).
 */
int loom_floor_div(int64_t a, int64_t b, int64_t *out);

/**
 * Order initiative entries supplied as a checked little-endian byte buffer; write
 * the ordered ids into `out_ids` (capacity `out_cap`, which MUST be >= the entry
 * count). Returns 0 on success; -1 on a null pointer / out_cap < count / count too
 * large / header < 4 bytes; -4 on a truncated buffer (header count exceeds the
 * bytes provided).
 *
 * Buffer layout (all little-endian, no padding):
 *   [0..4)   u32  entry count C
 *   then C records of 32 bytes each:
 *     [+0..8)   i64  id        [+8..16)  i64  total
 *     [+16..24) i64  modifier  [+24..32) i64  d20
 *
 * Codex hardening 2026-06-07: this REPLACES the old `#[repr(C)] LoomInitiativeEntry`
 * struct-array ABI - the hardened FFI boundary passes only flat byte buffers + opaque
 * handles, never raw structs by value (no padding/layout traps). The whole body is
 * catch_unwind-guarded (a panic across extern "C" is UB) and every read is bounds-
 * checked. Tiebreak: total/modifier/d20 DESC, then a numeric-aware id compare. (The
 * value-returning primitive exports - band/roll/pcg32 - are total integer arithmetic
 * with no panic surface and a non-c_int return, so they need no guard.)
 *
 * # Safety
 * `buf_ptr` points to `buf_len` readable bytes (null only if `buf_len == 0`);
 * `out_ids` points to writable storage for at least `out_cap` `i64`.
 */
int loom_initiative_order_n(const uint8_t *buf_ptr,
                            uintptr_t buf_len,
                            int64_t *out_ids,
                            uintptr_t out_cap);

/**
 * HMAC-SHA256 of `message` under `key` -> 64-char lowercase hex written to `out`
 * (cap >= 65, includes the NUL). Returns 64, or -1 on a bad arg / non-UTF-8
 * message. Byte-identical to the TS + Python + native chains.
 *
 * # Safety
 * `key` must point to `key_len` bytes; `message` must be a NUL-terminated C
 * string; `out` must be writable for `out_cap` bytes.
 */
int loom_hmac_sha256_hex(const uint8_t *key,
                         uintptr_t key_len,
                         const char *message,
                         char *out,
                         uintptr_t out_cap);

/**
 * HMAC-SHA256 over RAW message bytes (ptr + len) -> 64-char hex into `out` (cap
 * >= 65). Unlike the C-string form above, this hashes interior NUL and non-UTF-8
 * bytes faithfully (Codex P2). Returns 64, or -1 on a bad arg.
 *
 * # Safety
 * `key` points to `key_len` bytes; `message` points to `message_len` bytes (may
 * be null only if message_len == 0); `out` is writable for `out_cap` bytes.
 */
int loom_hmac_sha256_hex_raw(const uint8_t *key,
                             uintptr_t key_len,
                             const uint8_t *message,
                             uintptr_t message_len,
                             char *out,
                             uintptr_t out_cap);

/**
 * Sign one event record -> 64-char hex into `out` (cap >= 65). `payload_json` is
 * a JSON string. Returns 64; -1 bad arg / non-UTF-8; -2 invalid JSON; -3
 * non-canonicalizable payload (e.g. a fractional number).
 *
 * # Safety
 * `key` points to `key_len` bytes; `type_`, `payload_json`, `prev_sig` are
 * NUL-terminated C strings; `out` is writable for `out_cap` bytes.
 */
int loom_sign_record(const uint8_t *key,
                     uintptr_t key_len,
                     uint64_t seq,
                     const char *type_,
                     const char *payload_json,
                     const char *prev_sig,
                     char *out,
                     uintptr_t out_cap);

/**
 * Bounded-read variant of `loom_world_state_hash` - `state_ptr` points to `state_len`
 * JSON bytes (no NUL terminator required). The safe ABI for the world-state hash.
 * Codex P1.
 *
 * # Safety
 * `key` points to `key_len` bytes; `state_ptr` points to `state_len` readable bytes
 * (null only if `state_len == 0`); `out` is writable for `out_cap` bytes.
 */
int loom_world_state_hash_n(const uint8_t *key,
                            uintptr_t key_len,
                            const uint8_t *state_ptr,
                            uintptr_t state_len,
                            char *out,
                            uintptr_t out_cap);

/**
 * Bounded-read variant of `loom_global_region_hash` - `regions_ptr` points to
 * `regions_len` JSON bytes (no NUL terminator required). The safe ABI. Codex P1.
 *
 * # Safety
 * `key` points to `key_len` bytes; `regions_ptr` points to `regions_len` readable
 * bytes (null only if `regions_len == 0`); `out` is writable for `out_cap` bytes.
 */
int loom_global_region_hash_n(const uint8_t *key,
                              uintptr_t key_len,
                              const uint8_t *regions_ptr,
                              uintptr_t regions_len,
                              char *out,
                              uintptr_t out_cap);

/**
 * Bounded-read variant of `loom_tick_epoch` - `input_ptr` points to `input_len` JSON
 * bytes (no NUL terminator required). Codex P1.
 *
 * # Safety
 * `input_ptr` points to `input_len` readable bytes; `out` is writable for `out_cap`.
 */
int loom_tick_epoch_n(const uint8_t *input_ptr, uintptr_t input_len, char *out, uintptr_t out_cap);

/**
 * Bounded-read variant of `loom_catch_up_epochs`. Codex P1.
 *
 * # Safety
 * `input_ptr` points to `input_len` readable bytes; `out` is writable for `out_cap`.
 */
int loom_catch_up_epochs_n(const uint8_t *input_ptr,
                           uintptr_t input_len,
                           char *out,
                           uintptr_t out_cap);

/**
 * Bounded-read variant of `loom_resume_session`. Codex P1.
 *
 * # Safety
 * `input_ptr` points to `input_len` readable bytes; `out` is writable for `out_cap`.
 */
int loom_resume_session_n(const uint8_t *input_ptr,
                          uintptr_t input_len,
                          char *out,
                          uintptr_t out_cap);

/**
 * Bounded-read variant of `loom_tick_frame`. Codex P1.
 *
 * # Safety
 * `input_ptr` points to `input_len` readable bytes; `out` is writable for `out_cap`.
 */
int loom_tick_frame_n(const uint8_t *input_ptr, uintptr_t input_len, char *out, uintptr_t out_cap);

/**
 * Bounded-read variant of `loom_reconcile_frames`. Codex P1.
 *
 * # Safety
 * `input_ptr` points to `input_len` readable bytes; `out` is writable for `out_cap`.
 */
int loom_reconcile_frames_n(const uint8_t *input_ptr,
                            uintptr_t input_len,
                            char *out,
                            uintptr_t out_cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LOOM_ENGINE_H */
