/* loom_engine - C ABI for the Loom Engine deterministic core (Unity/C#, Godot, Go, C). One Rust core, byte-identical across every surface. */

#ifndef LOOM_ENGINE_H
#define LOOM_ENGINE_H

#pragma once

/* GENERATED by cbindgen - do not edit. Regenerate: cbindgen --config cbindgen.toml --crate loom_c_abi --output loom_engine.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Band codes (closeness ascending). Mirror loom_combat::range_bands.
 */
#define LOOM_BAND_ENGAGED 0

#define LOOM_BAND_NEAR 1

#define LOOM_BAND_FAR 2

/**
 * One initiative entry over the C ABI.
 */
typedef struct LoomInitiativeEntry {
  int64_t id;
  int64_t total;
  int64_t modifier;
  int64_t d20;
} LoomInitiativeEntry;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Library version as a borrowed, NUL-terminated static C string (never freed).
 */
const char *loom_version(void);

/**
 * Distance (feet) -> band code. Negative/uncomputable -> NEAR, like the core.
 */
int loom_band_from_distance_ft(int64_t feet);

/**
 * 1 iff `band` is at least as close as `max_band`; 0 otherwise / on a bad code.
 */
int loom_band_within(int band, int max_band);

/**
 * Deterministic single die [1, sides] from a fresh seed.
 */
uint32_t loom_roll_die(uint64_t seed, uint32_t sides);

/**
 * Deterministic sum of `count` dice of `sides` faces from a fresh seed.
 */
uint64_t loom_roll_dice(uint64_t seed, uint32_t count, uint32_t sides);

/**
 * Next raw u32 from a seeded PCG32 (for parity checks).
 */
uint32_t loom_pcg32_next(uint64_t seed);

/**
 * Python-floor division into `*out`. Returns 0 on success, -1 on a null out or
 * division by zero.
 *
 * # Safety
 * `out` must be a valid, writable `*mut i64` (or null, which returns -1).
 */
int loom_floor_div(int64_t a, int64_t b, int64_t *out);

/**
 * Order `n` entries; write the ordered ids into `out_ids` (capacity `out_cap`,
 * which MUST be >= n). Returns 0 on success, -1 on a null pointer / out_cap < n.
 * Tiebreak: total/modifier/d20 DESC, then a numeric-aware id compare.
 *
 * # Safety
 * `entries` must point to `n` initialized `LoomInitiativeEntry`; `out_ids` must
 * point to writable storage for at least `out_cap` `i64`, with `out_cap >= n`.
 */
int loom_initiative_order(const struct LoomInitiativeEntry *entries,
                          uintptr_t n,
                          int64_t *out_ids,
                          uintptr_t out_cap);

/**
 * HMAC-SHA256 of `message` under `key` -> 64-char lowercase hex written to `out`
 * (cap >= 65, includes the NUL). Returns 64, or -1 on a bad arg / non-UTF-8
 * message. Byte-identical to the TS + Python + native chains.
 *
 * # Safety
 * `key` must point to `key_len` bytes; `message` must be a NUL-terminated C
 * string; `out` must be writable for `out_cap` bytes.
 */
int loom_hmac_sha256_hex(const uint8_t *key,
                         uintptr_t key_len,
                         const char *message,
                         char *out,
                         uintptr_t out_cap);

/**
 * Sign one event record -> 64-char hex into `out` (cap >= 65). `payload_json` is
 * a JSON string. Returns 64; -1 bad arg / non-UTF-8; -2 invalid JSON; -3
 * non-canonicalizable payload (e.g. a fractional number).
 *
 * # Safety
 * `key` points to `key_len` bytes; `type_`, `payload_json`, `prev_sig` are
 * NUL-terminated C strings; `out` is writable for `out_cap` bytes.
 */
int loom_sign_record(const uint8_t *key,
                     uintptr_t key_len,
                     uint64_t seq,
                     const char *type_,
                     const char *payload_json,
                     const char *prev_sig,
                     char *out,
                     uintptr_t out_cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LOOM_ENGINE_H */
