//! Cross-language parity proof: the Rust loom_snapshot must reproduce the
//! TS-generated golden vector byte-for-byte - both the canonical encoding AND
//! the HMAC state hash. The vector (test_vectors/v3_0_snapshot_canonical.json)
//! is generated by `npx tsx tools/gen-snapshot-vectors.ts` running the real TS
//! implementation, then asserted here. A single-byte divergence (a key-sort, a
//! length-prefix, an integer bound) fails this test - including the strict
//! astral trap (U+1F40D vs U+F8FF, whose UTF-16 and UTF-8 orders invert).

use loom_snapshot::{canonical_world_state, world_state_hash};
use serde_json::Value;
use std::fs;

#[test]
fn golden_vector_byte_parity_with_ts() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_vectors/v3_0_snapshot_canonical.json"
    );
    let raw = fs::read_to_string(path).expect("read v3_0_snapshot_canonical.json");
    let v: Value = serde_json::from_str(&raw).expect("parse vector json");
    let cases = v["cases"].as_array().expect("cases array");
    assert!(cases.len() >= 5, "expected >= 5 golden cases");

    for c in cases {
        let label = c["label"].as_str().unwrap_or("?");
        let key = c["key"].as_str().expect("case key");
        let input = &c["input"];
        let exp_canon = c["expect_canonical"].as_str().expect("expect_canonical");
        let exp_hash = c["expect_hash"].as_str().expect("expect_hash");

        let canon = canonical_world_state(input)
            .unwrap_or_else(|e| panic!("canonical err on '{}': {:?}", label, e));
        assert_eq!(canon, exp_canon, "canonical mismatch: {}", label);

        let hash = world_state_hash(key.as_bytes(), input)
            .unwrap_or_else(|e| panic!("hash err on '{}': {:?}", label, e));
        assert_eq!(hash, exp_hash, "HASH PARITY BREAK: {}", label);
    }
}
