// pcg32.ts - PCG32 (XSH RR 64/32), the canonical deterministic PRNG.
//
// 3.0 primitive. The reference RNG every Loom surface reproduces bit-for-bit -
// the foundation of cross-language dice + the ruleset AST's randomness. Ported
// from the Rust loom_math::Pcg32; the legacy mulberry32 (entropy.ts) is for
// non-authoritative visual jitter only and is NOT this.
//
// The 64-bit LCG (state * 6364136223846793005 + inc) exceeds JS's 2^53 safe
// integer range, so the state arithmetic uses BigInt; outputs are u32 (plain
// numbers). Bit-identical to the Rust core and the Python port, pinned by
// test_vectors/v3_pcg32.json (generated by the authoritative Rust).
//
//   var r = Pcg32.seeded(42n);
//   r.nextU32();          // -> 1898997482  (matches Rust + Python)
//   r.rollDie(20);        // 1..=20, unbiased (rejection sampling)
//   r.rollDice(3, 6);     // sum of 3d6, deterministic roll order
//
// Code style: var-only in browser source.

var MASK64 = (1n << 64n) - 1n;
var MASK32 = 0xffffffffn;

export class Pcg32 {
  // The PCG multiplier constant (LCG step). MUST match Rust/Python.
  static MULT: bigint = 6364136223846793005n;
  // Default stream selector when only a seed is supplied.
  static DEFAULT_STREAM: bigint = 0xda3e39cb94b95bdbn;

  private state: bigint;
  private inc: bigint;

  // Construct from a seed + a stream selector (seq). Same seed, different stream
  // -> distinct, non-correlated sequences. Both are treated as u64 (masked).
  constructor(seed: bigint, seq: bigint) {
    this.state = 0n;
    this.inc = ((seq << 1n) | 1n) & MASK64;
    this.nextU32();
    this.state = (this.state + (seed & MASK64)) & MASK64;
    this.nextU32();
  }

  // Construct from a seed alone (uses DEFAULT_STREAM).
  static seeded(seed: bigint): Pcg32 {
    return new Pcg32(seed, Pcg32.DEFAULT_STREAM);
  }

  // The next 32-bit output + advance the state.
  nextU32(): number {
    var old = this.state;
    this.state = (old * Pcg32.MULT + this.inc) & MASK64;
    // XSH RR: xorshift the high bits, then a data-dependent rotate.
    var xorshifted = Number((((old >> 18n) ^ old) >> 27n) & MASK32);
    var rot = Number((old >> 59n) & MASK32); // 0..31
    return rotateRight32(xorshifted, rot);
  }

  // Uniform integer in [0, bound) with NO modulo bias (rejection sampling).
  // bound === 0 returns 0.
  boundedU32(bound: number): number {
    if (bound === 0) return 0;
    // threshold = (2^32 - bound) % bound, exactly as Rust bound.wrapping_neg() % bound.
    var threshold = (4294967296 - bound) % bound;
    for (;;) {
      var r = this.nextU32();
      if (r >= threshold) return r % bound;
    }
  }

  // Roll one die with `sides` faces -> 1..=sides. sides === 0 returns 0.
  rollDie(sides: number): number {
    if (sides === 0) return 0;
    return this.boundedU32(sides) + 1;
  }

  // Roll `count` dice of `sides` faces -> the sum. Deterministic roll order
  // (die 1, die 2, ...), so a replay reproduces it exactly.
  rollDice(count: number, sides: number): number {
    var total = 0;
    for (var i = 0; i < count; i++) {
      total += this.rollDie(sides);
    }
    return total;
  }
}

// u32 rotate-right by r (r is reduced mod 32). Unsigned 32-bit throughout.
function rotateRight32(x: number, r: number): number {
  r = r & 31;
  if (r === 0) return x >>> 0;
  return ((x >>> r) | (x << (32 - r))) >>> 0;
}
