// Ruleset-AST v2 golden-vector harness (docs/specs/AST-V2-SPEC.md).
//
// Loads test_vectors/ast_v2_families.json (generated by
// tools/gen-ast-v2-vectors.ts) and runs every case through the real evaluator
// with the spec section 1.3 scripted test PRNG: rollDie pops dice_stream
// entries in order, rollDie(0) returns 0 WITHOUT popping (mirroring production
// Pcg32), accept vectors must consume the stream fully, and reject vectors
// must reject AT VALIDATION - zero draws, state unchanged. Assertions follow
// the section 1.5 normative schema exactly: an absent expect field is not
// asserted; entities not listed in any *_after field are asserted unchanged;
// `reason` strings are informative only and never asserted. This runner is an
// independent implementation of the schema - it deliberately does NOT share
// code with the generator's verifier, so a bug in one cannot blind the other.

import { test } from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  applyTriggeredMutations, evaluateAction, validateCheck, validateTriggeredMutations,
} from '../src/runtime/ruleset-ast.js';
import type { MutationNode, CheckNode, EvalContext, AppliedMutation } from '../src/runtime/ruleset-ast.js';
import type { WorldState } from '../src/runtime/world-state-snapshot.js';
import type { Pcg32 } from '../src/runtime/pcg32.js';

var here = dirname(fileURLToPath(import.meta.url));
var vec = JSON.parse(readFileSync(join(here, '..', 'test_vectors', 'ast_v2_families.json'), 'utf8'));

interface VectorCase {
  label: string;
  context: string;
  actor: string;
  target?: string;
  state: WorldState;
  ast?: unknown;
  mutations?: unknown;
  raw_document?: string;
  dice_stream: number[];
  expect: Record<string, unknown>;
}

// Scripted test PRNG (spec 1.3): entry k is the k-th STREAM-CONSUMING rollDie
// call; zero-sides dice are CALLED but pop nothing; out-of-range entries and
// an exhausted stream are harness failures.
function scriptedRng(stream: number[], label: string): { rng: Pcg32; consumed(): number } {
  var i = 0;
  var fake = {
    rollDie: function (sides: number): number {
      if (sides === 0) return 0;
      assert.ok(i < stream.length, label + ': dice stream exhausted (implementation over-draws)');
      var v = stream[i] as number;
      i++;
      assert.ok(v >= 1 && v <= sides, label + ': stream entry ' + v + ' out of range for d' + sides);
      return v;
    },
  };
  return { rng: fake as unknown as Pcg32, consumed: function () { return i; } };
}

function has(obj: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(obj, key);
}

function runCase(v: VectorCase): void {
  var label = v.label;
  var pre = JSON.stringify(v.state);
  // raw_document vectors (F7): parse THIS string with the surface's standard
  // JSON parser and ignore the ast / mutations fields (spec 1.5).
  var doc: unknown = v.raw_document !== undefined ? JSON.parse(v.raw_document)
    : (v.context === 'check' ? v.ast : v.mutations);
  var sr = scriptedRng(v.dice_stream, label);
  var ctx: EvalContext = {
    state: v.state, actorId: v.actor, targetId: v.target, rng: sr.rng,
    naturalRoll: null, eachId: undefined,
  };
  var ex = v.expect;

  if (ex.reject === true) {
    assert.throws(function () {
      if (v.context === 'check') evaluateAction(v.state, doc as CheckNode, ctx);
      else applyTriggeredMutations(v.state, doc as MutationNode[], ctx);
    }, label + ': must reject');
    assert.strictEqual(sr.consumed(), 0, label + ': reject consumes zero PRNG draws');
    assert.strictEqual(JSON.stringify(v.state), pre, label + ': reject leaves state unchanged');
    return;
  }

  var endState: WorldState;
  var applied: AppliedMutation[];
  if (v.context === 'check') {
    var r = evaluateAction(v.state, doc as CheckNode, ctx);
    endState = r.state; applied = r.mutations;
    assert.ok(has(ex, 'degree'), label + ': check-context vectors require expect.degree');
    assert.strictEqual(r.degree, ex.degree, label + ': degree');
    if (has(ex, 'roll')) assert.strictEqual(r.roll, ex.roll, label + ': roll');
    if (has(ex, 'dc')) assert.strictEqual(r.dc, ex.dc, label + ': dc');
    if (has(ex, 'delta')) assert.strictEqual(r.delta, ex.delta, label + ': delta');
    if (has(ex, 'natural')) assert.strictEqual(r.natural, ex.natural, label + ': natural');
  } else {
    var rt = applyTriggeredMutations(v.state, doc as MutationNode[], ctx);
    endState = rt.state; applied = rt.mutations;
  }
  // Accept vectors MUST consume the stream fully (this is how the
  // "untaken branches consume zero RNG" pins work - spec 1.3).
  assert.strictEqual(sr.consumed(), v.dice_stream.length, label + ': dice stream fully consumed');
  if (has(ex, 'rng_draws_total')) {
    assert.strictEqual(sr.consumed(), ex.rng_draws_total, label + ': rng_draws_total');
  }
  assert.strictEqual(JSON.stringify(v.state), pre, label + ': input state never mutated');

  var listed: Record<string, boolean> = {};
  var id: string;
  if (has(ex, 'props_after')) {
    var propsAfter = ex.props_after as Record<string, Record<string, number>>;
    for (id in propsAfter) {
      listed[id] = true;
      var entP = endState.entities[id];
      assert.ok(entP, label + ': props_after entity ' + id + ' exists');
      assert.deepStrictEqual(entP.properties, propsAfter[id], label + ': props_after ' + id);
    }
  }
  if (has(ex, 'tags_after')) {
    var tagsAfter = ex.tags_after as Record<string, string[]>;
    for (id in tagsAfter) {
      listed[id] = true;
      var entT = endState.entities[id];
      assert.ok(entT, label + ': tags_after entity ' + id + ' exists');
      assert.deepStrictEqual(entT.tags, tagsAfter[id], label + ': tags_after ' + id);
    }
  }
  if (has(ex, 'hp_after')) {
    var hpAfter = ex.hp_after as Record<string, number>;
    for (id in hpAfter) {
      listed[id] = true;
      var entH = endState.entities[id];
      assert.ok(entH, label + ': hp_after entity ' + id + ' exists');
      assert.strictEqual(entH.properties.hp, hpAfter[id], label + ': hp_after ' + id);
    }
  }
  // Entities NOT listed in any *_after field are asserted UNCHANGED (spec 1.5).
  for (id in v.state.entities) {
    if (!listed[id]) {
      assert.deepStrictEqual(endState.entities[id], v.state.entities[id], label + ': entity ' + id + ' unchanged');
    }
  }
  if (has(ex, 'applied')) {
    assert.deepStrictEqual(applied, ex.applied, label + ': applied list (exact order)');
  }
  if (has(ex, 'applied_count')) {
    assert.strictEqual(applied.length, ex.applied_count, label + ': applied_count');
  }
}

test('AST v2 golden vectors: every spec-enumerated case (A-F, H1, S12, S13) matches', function () {
  assert.ok(Array.isArray(vec.cases), 'vector file has a cases array');
  assert.ok(vec.cases.length >= 38, 'expected >= 38 v2 golden cases, got ' + vec.cases.length);
  for (var i = 0; i < vec.cases.length; i++) {
    runCase(vec.cases[i] as VectorCase);
  }
});

// Normative spec behaviors a scripted-stream vector cannot express (they pin
// THROW classes, not resolutions): short-circuit observability (spec 3.2),
// the both-operands rule (4.2 step 1), the delta exactness amendment (4.2),
// the MAX_WORLD_ENTITIES runtime cap (6.2/8.7), the mutation-structure depth
// counter (8.3), and the has_tag `each` static scope rule (4.6).
test('AST v2 normative pins: short-circuit, both-operands, delta exactness, entity cap, depth, each scope', function () {
  var MAXI = 9007199254740991;

  // 3.2: a decided `and` MUST NOT resolve operands of later children - the
  // missing-target throw in child 2 must never fire once child 1 is false.
  var sAnd: WorldState = { epoch: 0, worldSeed: 0, entities: { a: { properties: { hp: 1 }, tags: [] } } };
  var andCheck = { type: 'check', roll: { type: 'literal', value: 1 }, dc: { type: 'literal', value: 0 },
    degrees: { success: { condition: { type: 'and', conditions: [
      { type: 'delta_gte', value: 999 },
      { type: 'compare', op: 'gte', left: { source: 'prop', target: 'target', property: 'hp' }, right: { source: 'literal', value: 0 } }] },
      mutations: [] } } } as unknown as CheckNode;
  var rAnd = evaluateAction(sAnd, andCheck, { state: sAnd, actorId: 'a', targetId: undefined, rng: scriptedRng([], 'and-sc').rng, naturalRoll: null, eachId: undefined });
  assert.strictEqual(rAnd.degree, 'none', 'short-circuited and returns the decided result, no throw');

  // 3.2 (made normative for v1 `or` too): a decided `or` never reaches child 2.
  var orCheck = { type: 'check', roll: { type: 'literal', value: 1 }, dc: { type: 'literal', value: 0 },
    degrees: { success: { condition: { type: 'or', conditions: [
      { type: 'delta_gte', value: 0 },
      { type: 'compare', op: 'gte', left: { source: 'prop', target: 'target', property: 'hp' }, right: { source: 'literal', value: 0 } }] },
      mutations: [] } } } as unknown as CheckNode;
  var rOr = evaluateAction(sAnd, orCheck, { state: sAnd, actorId: 'a', targetId: undefined, rng: scriptedRng([], 'or-sc').rng, naturalRoll: null, eachId: undefined });
  assert.strictEqual(rOr.degree, 'success', 'short-circuited or returns the decided result, no throw');

  // 4.2 step 1: BOTH operands are ALWAYS resolved, left then right - a null
  // left (diceless natural) does NOT skip the right operand's missing-target throw.
  var bothCheck = { type: 'check', roll: { type: 'literal', value: 1 }, dc: { type: 'literal', value: 0 },
    degrees: { success: { condition: { type: 'compare', op: 'gte',
      left: { source: 'natural' },
      right: { source: 'prop', target: 'target', property: 'hp' } },
      mutations: [] } } } as unknown as CheckNode;
  assert.throws(function () {
    evaluateAction(sAnd, bothCheck, { state: sAnd, actorId: 'a', targetId: undefined, rng: scriptedRng([], 'both').rng, naturalRoll: null, eachId: undefined });
  }, /target/, 'null left operand must still resolve the right operand');

  // 4.2 delta exactness: |roll - dc| > 2^53 - 1 is a RUNTIME error (validation
  // passes - both literals are individually JS-safe).
  var deltaCheck = { type: 'check', roll: { type: 'literal', value: MAXI }, dc: { type: 'literal', value: -MAXI },
    degrees: { success: { condition: { type: 'delta_gte', value: 0 }, mutations: [] } } } as unknown as CheckNode;
  assert.doesNotThrow(function () { validateCheck(deltaCheck); }, 'unsafe delta is NOT a validation reject');
  assert.throws(function () {
    evaluateAction(sAnd, deltaCheck, { state: sAnd, actorId: 'a', targetId: undefined, rng: scriptedRng([], 'delta').rng, naturalRoll: null, eachId: undefined });
  }, /delta/, 'unsafe delta throws at runtime');

  // 6.2 / 8.7: MAX_WORLD_ENTITIES (65536) is a runtime cap at foreach SELECT -
  // exactly 65536 entities pass, 65537 throw.
  function bigState(n: number): WorldState {
    var ents: Record<string, { properties: Record<string, number>; tags: string[] }> = {};
    ents['foe_one'] = { properties: { hp: 5 }, tags: ['foe'] };
    for (var i = 1; i < n; i++) ents['e' + i] = { properties: {}, tags: [] };
    return { epoch: 0, worldSeed: 0, entities: ents } as WorldState;
  }
  var capMuts = [{ type: 'foreach_target', select: { tag: 'foe' },
    mutations: [{ type: 'sub_prop', target: 'each', property: 'hp', value: { type: 'literal', value: 1 } }] }] as unknown as MutationNode[];
  var atCap = bigState(65536);
  var okRun = applyTriggeredMutations(atCap, capMuts, { state: atCap, actorId: 'foe_one', targetId: undefined, rng: scriptedRng([], 'cap-ok').rng, naturalRoll: null, eachId: undefined });
  assert.strictEqual(okRun.state.entities['foe_one']!.properties.hp, 4, '65536 entities is within the cap');
  var overCap = bigState(65537);
  assert.throws(function () {
    applyTriggeredMutations(overCap, capMuts, { state: overCap, actorId: 'foe_one', targetId: undefined, rng: scriptedRng([], 'cap-over').rng, naturalRoll: null, eachId: undefined });
  }, /MAX_WORLD_ENTITIES/, '65537 entities throws at SELECT');

  // 8.3: the mutation-structure depth counter - 16 nested bodies accept,
  // 17 reject at validation.
  function nestRepeats(n: number): MutationNode[] {
    var inner: unknown[] = [];
    for (var i = 0; i < n; i++) inner = [{ type: 'repeat', count: 1, mutations: inner }];
    return inner as MutationNode[];
  }
  assert.doesNotThrow(function () { validateTriggeredMutations(nestRepeats(16)); }, '16-deep structure accepts');
  assert.throws(function () { validateTriggeredMutations(nestRepeats(17)); }, /depth/, '17-deep structure rejects');

  // 4.6: has_tag with `each` outside any foreach_target body rejects statically.
  assert.throws(function () {
    validateTriggeredMutations([{ type: 'if',
      condition: { type: 'has_tag', target: 'each', tag: 'x' }, then: [] }] as unknown as MutationNode[]);
  }, /each/, 'has_tag each outside foreach scope rejects');
});

test('AST v2 vector file: schema sanity (contexts, reject pins, F7 lexical form survives)', function () {
  var sawCheck = false; var sawTrigger = false; var sawRaw = false; var rejects = 0;
  for (var i = 0; i < vec.cases.length; i++) {
    var c = vec.cases[i] as VectorCase;
    assert.ok(c.context === 'check' || c.context === 'trigger', c.label + ': context');
    assert.ok(typeof c.actor === 'string' && c.actor.length > 0, c.label + ': actor required');
    assert.ok(Array.isArray(c.dice_stream), c.label + ': dice_stream required');
    if (c.context === 'check') sawCheck = true; else sawTrigger = true;
    if (c.raw_document !== undefined) {
      sawRaw = true;
      // A canonicalizing reserialization would erase the lexical form under
      // test - the raw text must still carry the non-canonical "3.0".
      assert.ok(c.raw_document.indexOf('3.0') >= 0, c.label + ': raw_document keeps the lexical 3.0');
      assert.strictEqual(c.ast, undefined, c.label + ': raw_document vectors carry no parsed ast');
      assert.strictEqual(c.mutations, undefined, c.label + ': raw_document vectors carry no parsed mutations');
    }
    if (c.expect.reject === true) {
      rejects++;
      // Spec 1.5: all three reject fields are REQUIRED on reject vectors.
      assert.strictEqual(c.expect.rng_draws_total, 0, c.label + ': reject pins rng_draws_total 0');
      assert.strictEqual(c.expect.state_unchanged, true, c.label + ': reject pins state_unchanged');
    } else if (c.context === 'check') {
      assert.ok(typeof c.expect.degree === 'string', c.label + ': accept check vectors require degree');
    }
  }
  assert.ok(sawCheck && sawTrigger, 'both validation contexts are exercised');
  assert.ok(sawRaw, 'the raw_document lexical-form vector (F7) is present');
  assert.ok(rejects >= 8, 'expected >= 8 reject vectors, got ' + rejects);
});
