//! loom_events - tamper-evident, HMAC-SHA256-chained event log (Rust core).
//!
//! The native sibling of the engine's TS `EventChain` (src/runtime/event-chain.ts)
//! and the server-authoritative event tape that guards TheWorldTable's combat +
//! currency ledger. Every record is signed with HMAC-SHA256 and folds in the
//! PREVIOUS record's signature, so the whole log is a hash chain: field tampering,
//! deletion, reordering, and (with a seal) tail truncation all break verification.
//!
//! BYTE-COMPATIBLE WITH THE TS CHAIN. The TS source carries a "not promised
//! byte-compatible with other languages" disclaimer - but its canonical message
//! format is in fact fully deterministic, and this crate reproduces it EXACTLY so
//! a record signed here verifies in TS and vice-versa. The three cross-language
//! traps and how each is defeated:
//!
//!   1. `field(s) = s.length + ':' + s` uses the JS UTF-16 string length, NOT the
//!      UTF-8 byte length - so `field()` here counts `s.encode_utf16().count()`.
//!   2. The canonical string form is JS `JSON.stringify(s)` - hand-written below
//!      (`js_json_string`) to match its exact escape set, NOT serde_json's.
//!   3. Object keys are sorted by JS `Array.sort()` order (UTF-16 code units),
//!      reproduced by sorting on `encode_utf16()` - not Rust's default scalar Ord
//!      (the two differ only for astral-plane keys, which event data never uses,
//!      but we match anyway).
//!
//! The shared golden vectors (test_vectors/event_chain_v1.json) are GENERATED by
//! running the real TS, then asserted by both the TS and the Rust test harness -
//! a real parity proof, not a hand-copied constant.
//!
//! FLOAT BOUNDARY (honest scope): a signed payload's numbers must be integers.
//! Integral floats (`7.0`) canonicalize as integers (matching JS `String(7.0) ===
//! "7"`); a real fraction is rejected fail-closed, because matching V8's
//! shortest-float dtoa is out of scope AND the determinism rule bans fractions
//! from signed event data. The numeric core (loom_math) is integer-only for the
//! same reason.

use hmac::{Hmac, Mac};
use serde_json::Value;
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

// Domain tags - record sigs and seal sigs live in separate namespaces so a
// record HMAC can never be reinterpreted as a seal HMAC. Trailing /1 is a format
// version. MUST match the TS constants verbatim.
const RECORD_DOMAIN: &str = "loom.chain.rec/1";
const SEAL_DOMAIN: &str = "loom.chain.seal/1";

// Hard cap on canonicalization recursion - matches the TS MAX_CANONICAL_DEPTH so
// a hostile deeply-nested payload is rejected at the same boundary on both sides.
const MAX_CANONICAL_DEPTH: usize = 256;

/// A payload the chain refuses to sign. serde_json::Value cannot hold the
/// NaN/Infinity/symbol/Date/function shapes the TS rejects, so those rejections
/// are simply unrepresentable here; only these two remain.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CanonError {
    /// A number with a real fractional part (see the FLOAT BOUNDARY note).
    NonIntegerNumber,
    /// An integer outside JS's safe range [-(2^53-1), 2^53-1]. TS canonicalizes
    /// via JSON.parse, which silently rounds beyond 2^53 (9007199254740993 ->
    /// ...992), so signing such a value here would diverge from TS. Reject to
    /// keep the accepted numeric surface JS-safe-integer-only (Codex P1).
    UnsafeInteger,
    /// Negative zero (-0.0). TS rejects it fail-closed; we match (a signed 0 must
    /// not be mutable to -0 and still verify).
    NegativeZero,
    /// An own "__proto__" data key. TS rejects it (a JSON-parsed __proto__ cannot
    /// round-trip through a normal-prototype clone); we match for parity.
    ForbiddenKey,
    /// Payload nesting exceeds MAX_CANONICAL_DEPTH.
    DepthExceeded,
}

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/// HMAC-SHA256 -> 64-char lowercase hex. The algorithm is FIPS/RFC-standardized,
/// so this is byte-identical to the engine's hand-rolled TS hmacSha256Hex for the
/// same (key, message) bytes (proven by the RFC 4231 test vector below).
pub fn hmac_sha256_hex(key: &[u8], message: &str) -> String {
    hmac_sha256_hex_bytes(key, message.as_bytes())
}

/// HMAC-SHA256 over RAW message bytes (may contain interior NUL / non-UTF-8) ->
/// 64-char lowercase hex. The &str form above is just this with message.as_bytes().
pub fn hmac_sha256_hex_bytes(key: &[u8], message: &[u8]) -> String {
    let mut mac =
        <HmacSha256 as Mac>::new_from_slice(key).expect("HMAC accepts a key of any length");
    mac.update(message);
    let out = mac.finalize().into_bytes();
    let mut hex = String::with_capacity(64);
    for b in out.iter() {
        hex.push_str(&format!("{:02x}", b));
    }
    hex
}

/// JS String.length = UTF-16 code-unit count (NOT bytes, NOT scalar count).
fn utf16_len(s: &str) -> usize {
    s.encode_utf16().count()
}

/// Length-prefixed field `<utf16len>:<value>` - self-delimiting, so concatenating
/// fields is injective (a value cannot forge a boundary). Matches TS `field()`.
fn field(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    out.push_str(&utf16_len(s).to_string());
    out.push(':');
    out.push_str(s);
    out
}

/// Exactly JS `JSON.stringify(s)` for a string (including the surrounding quotes):
/// escape `"` `\` and the C0 control set (\b \t \n \f \r, else \u00xx lowercase);
/// every other code point - including all non-ASCII and DEL - is emitted literally.
/// Rust &str is always valid UTF-8, so there are no lone surrogates to reject.
fn js_json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{0008}' => out.push_str("\\b"),
            '\u{0009}' => out.push_str("\\t"),
            '\u{000A}' => out.push_str("\\n"),
            '\u{000C}' => out.push_str("\\f"),
            '\u{000D}' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// JS Number.MAX_SAFE_INTEGER (2^53 - 1). Beyond this JS integers are not exact,
/// so the signed numeric surface is restricted to [-MAX_SAFE_INT, MAX_SAFE_INT].
const MAX_SAFE_INT: i64 = 9_007_199_254_740_991;

#[inline]
fn safe_int(i: i64) -> Result<String, CanonError> {
    if (-MAX_SAFE_INT..=MAX_SAFE_INT).contains(&i) {
        Ok(i.to_string())
    } else {
        Err(CanonError::UnsafeInteger)
    }
}

/// JS `String(n)` for a JSON number, restricted to JS-SAFE integers (Codex P1:
/// TS canonicalizes through JSON.parse, which rounds past 2^53). See FLOAT BOUNDARY.
#[allow(clippy::float_cmp)]
fn canonical_number(n: &serde_json::Number) -> Result<String, CanonError> {
    if let Some(i) = n.as_i64() {
        return safe_int(i);
    }
    if let Some(u) = n.as_u64() {
        // u64 above i64::MAX is automatically > MAX_SAFE_INT -> rejected.
        return if u <= MAX_SAFE_INT as u64 {
            Ok(u.to_string())
        } else {
            Err(CanonError::UnsafeInteger)
        };
    }
    if let Some(f) = n.as_f64() {
        if f.is_finite() {
            // Codex P0: reject -0.0 to match the TS surface (Object.is(v, -0)).
            if f == 0.0 && f.is_sign_negative() {
                return Err(CanonError::NegativeZero);
            }
            // Round-trip through an integer cast (no float arithmetic): if the
            // value survives, it is an exact integer and stringifies like one,
            // matching JS where 7.0 and 7 are the same number -> "7". The
            // safe-integer bound then matches TS Number.isSafeInteger.
            let i = f as i64;
            if i as f64 == f {
                return safe_int(i);
            }
            if f >= 0.0 {
                let u = f as u64;
                if u as f64 == f {
                    return if u <= MAX_SAFE_INT as u64 {
                        Ok(u.to_string())
                    } else {
                        Err(CanonError::UnsafeInteger)
                    };
                }
            }
        }
    }
    Err(CanonError::NonIntegerNumber)
}

/// Deterministic STRICT JSON: object keys sorted (UTF-16 order), no whitespace,
/// fail-closed on a non-integer number. Mirrors TS `canonicalJson`.
fn canonical_json(value: &Value, depth: usize) -> Result<String, CanonError> {
    if depth > MAX_CANONICAL_DEPTH {
        return Err(CanonError::DepthExceeded);
    }
    match value {
        Value::Null => Ok("null".to_string()),
        Value::Bool(b) => Ok(if *b { "true" } else { "false" }.to_string()),
        Value::String(s) => Ok(js_json_string(s)),
        Value::Number(n) => canonical_number(n),
        Value::Array(arr) => {
            let mut items: Vec<String> = Vec::with_capacity(arr.len());
            for v in arr {
                items.push(canonical_json(v, depth + 1)?);
            }
            Ok(format!("[{}]", items.join(",")))
        }
        Value::Object(map) => {
            // Codex P0: reject an own "__proto__" data key to match TS.
            if map.contains_key("__proto__") {
                return Err(CanonError::ForbiddenKey);
            }
            // Sort by UTF-16 code-unit sequence to match JS Object.keys().sort().
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort_by(|a, b| a.encode_utf16().cmp(b.encode_utf16()));
            let mut pairs: Vec<String> = Vec::with_capacity(keys.len());
            for k in keys {
                let mut pair = js_json_string(k);
                pair.push(':');
                pair.push_str(&canonical_json(&map[k], depth + 1)?);
                pairs.push(pair);
            }
            Ok(format!("{{{}}}", pairs.join(",")))
        }
    }
}

/// The exact injective string fed to HMAC for one record. Matches TS
/// `canonicalMessage`: domain + seq + type + canonical(payload) + prevSig, each
/// length-prefixed.
fn canonical_message(
    seq: u64,
    type_: &str,
    payload: &Value,
    prev_sig: &str,
) -> Result<String, CanonError> {
    let mut msg = String::new();
    msg.push_str(&field(RECORD_DOMAIN));
    msg.push_str(&field(&seq.to_string()));
    msg.push_str(&field(type_));
    msg.push_str(&field(&canonical_json(payload, 0)?));
    msg.push_str(&field(prev_sig));
    Ok(msg)
}

fn seal_message(count: u64, head: &str) -> String {
    let mut m = String::new();
    m.push_str(&field(SEAL_DOMAIN));
    m.push_str(&field(&count.to_string()));
    m.push_str(&field(head));
    m
}

/// The HMAC hex signature for one record, byte-identical to the TS per-record
/// `sig`. Errors only if the payload is non-canonicalizable (see CanonError).
/// This is the parity-critical primitive the golden vectors lock down.
pub fn sign_record(
    key: &[u8],
    seq: u64,
    type_: &str,
    payload: &Value,
    prev_sig: &str,
) -> Result<String, CanonError> {
    Ok(hmac_sha256_hex(key, &canonical_message(seq, type_, payload, prev_sig)?))
}

/// Constant-time hex/byte equality - length is not secret (early-return), the
/// rest is xor-accumulated so no early exit leaks a match prefix. Mirrors TS
/// `timingSafeEqualHex`.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff: u8 = 0;
    for i in 0..a.len() {
        diff |= a[i] ^ b[i];
    }
    diff == 0
}

// ---------------------------------------------------------------------------
// EventChain
// ---------------------------------------------------------------------------

/// One signed record. Field names mirror the TS ChainedRecord (`type` is `type_`
/// here because `type` is a Rust keyword).
#[derive(Debug, Clone)]
pub struct ChainedRecord {
    pub seq: u64,
    pub type_: String,
    pub payload: Value,
    pub prev_sig: String,
    pub sig: String,
}

/// A signed (count, head) commitment - persist out of band to later detect tail
/// truncation. Mirrors TS ChainSeal.
#[derive(Debug, Clone)]
pub struct ChainSeal {
    pub count: u64,
    pub head: String,
    pub sig: String,
}

/// Tamper-evident HMAC-chained event log. `create -> append* -> verify / seal`.
pub struct EventChain {
    records: Vec<ChainedRecord>,
    key: Vec<u8>,
    genesis: String,
    head_sig: String,
    next_seq: u64,
}

impl EventChain {
    /// New empty chain. `genesis` is the root prevSig for the first record (binds
    /// the chain to a context, e.g. a world seed); pass "" for the default.
    pub fn create(key: &[u8], genesis: &str) -> Self {
        EventChain {
            records: Vec::new(),
            key: key.to_vec(),
            genesis: genesis.to_string(),
            head_sig: genesis.to_string(),
            next_seq: 1,
        }
    }

    /// Append + sign a record. Returns the stored record, or None on rejection
    /// (empty type / non-canonicalizable payload) WITHOUT advancing the sequence -
    /// fail-closed, exactly like the TS append.
    pub fn append(&mut self, type_: &str, payload: Value) -> Option<&ChainedRecord> {
        if type_.is_empty() {
            return None;
        }
        let seq = self.next_seq;
        let prev_sig = self.head_sig.clone();
        let sig = match sign_record(&self.key, seq, type_, &payload, &prev_sig) {
            Ok(s) => s,
            Err(_) => return None,
        };
        self.records.push(ChainedRecord {
            seq,
            type_: type_.to_string(),
            payload,
            prev_sig,
            sig: sig.clone(),
        });
        self.next_seq = seq + 1;
        self.head_sig = sig;
        self.records.last()
    }

    /// Current head signature - the value the NEXT append folds in. Equals the
    /// genesis anchor when empty.
    pub fn head(&self) -> &str {
        &self.head_sig
    }

    pub fn size(&self) -> usize {
        self.records.len()
    }

    pub fn records(&self) -> &[ChainedRecord] {
        &self.records
    }

    /// Recompute every signature AND verify chain linkage. true iff intact.
    pub fn verify(&self) -> bool {
        Self::verify_records(&self.key, &self.records, &self.genesis)
    }

    /// Verify an external record set (e.g. loaded from disk) without an instance.
    pub fn verify_records(key: &[u8], records: &[ChainedRecord], genesis: &str) -> bool {
        let mut prev_actual = genesis.to_string();
        for rec in records {
            let expected = match sign_record(key, rec.seq, &rec.type_, &rec.payload, &rec.prev_sig)
            {
                Ok(s) => s,
                Err(_) => return false, // stored record no longer canonicalizable
            };
            if !constant_time_eq(expected.as_bytes(), rec.sig.as_bytes()) {
                return false;
            }
            if rec.prev_sig != prev_actual {
                return false; // deletion / reordering broke the link
            }
            prev_actual = rec.sig.clone();
        }
        true
    }

    /// Sign the current (count, head) so a holder can later prove no records were
    /// dropped off the END. Persist out of band.
    pub fn seal(&self) -> ChainSeal {
        let count = self.records.len() as u64;
        let head = self.head_sig.clone();
        let sig = hmac_sha256_hex(&self.key, &seal_message(count, &head));
        ChainSeal { count, head, sig }
    }

    /// Verify a seal's own signature (constant-time).
    pub fn verify_seal(key: &[u8], seal: &ChainSeal) -> bool {
        let expected = hmac_sha256_hex(key, &seal_message(seal.count, &seal.head));
        constant_time_eq(expected.as_bytes(), seal.sig.as_bytes())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn hmac_matches_rfc4231_case2() {
        // RFC 4231 Test Case 2 - proves the HMAC-SHA256 primitive is correct, so
        // any byte-match with TS reduces purely to the canonical-message bytes.
        let got = hmac_sha256_hex(b"Jefe", "what do ya want for nothing?");
        assert_eq!(
            got,
            "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843"
        );
    }

    #[test]
    fn canonical_json_sorts_keys_and_escapes() {
        // Keys sorted; string escaped; integer (not 7.0) stringified plainly.
        let v = json!({ "b": "x\ty", "a": 7, "c": [1, 2] });
        assert_eq!(
            canonical_json(&v, 0).unwrap(),
            "{\"a\":7,\"b\":\"x\\ty\",\"c\":[1,2]}"
        );
    }

    #[test]
    fn integral_float_stringifies_as_integer() {
        assert_eq!(canonical_json(&json!(7.0), 0).unwrap(), "7");
        // A real fraction is rejected fail-closed.
        assert_eq!(canonical_json(&json!(7.5), 0), Err(CanonError::NonIntegerNumber));
    }

    #[test]
    fn rejects_ts_forbidden_shapes() {
        // Codex P0 parity: -0.0 and an own __proto__ key are rejected, matching TS.
        assert_eq!(
            canonical_json(&json!(-0.0), 0),
            Err(CanonError::NegativeZero)
        );
        let proto = serde_json::from_str::<Value>("{\"__proto__\":{\"x\":1}}").unwrap();
        assert_eq!(canonical_json(&proto, 0), Err(CanonError::ForbiddenKey));
        // sign_record surfaces the rejection (no signature for a forbidden payload).
        assert!(sign_record(b"k", 1, "t", &json!(-0.0), "").is_err());
    }

    #[test]
    fn rejects_unsafe_js_integers() {
        // Codex P1: integers beyond JS's safe range would round in TS's JSON.parse,
        // so signing them here would diverge. 2^53-1 is the last safe value.
        assert_eq!(canonical_json(&json!(9007199254740991_i64), 0).unwrap(), "9007199254740991");
        assert_eq!(canonical_json(&json!(-9007199254740991_i64), 0).unwrap(), "-9007199254740991");
        for &bad in &[9007199254740992_i64, 9007199254740993_i64, -9007199254740992_i64] {
            assert_eq!(
                canonical_json(&json!(bad), 0),
                Err(CanonError::UnsafeInteger),
                "{} must be rejected as JS-unsafe",
                bad
            );
        }
    }

    #[test]
    fn field_counts_utf16_units_not_bytes() {
        // An astral char is 1 scalar / 4 UTF-8 bytes / 2 UTF-16 units (JS .length).
        assert_eq!(field("\u{1F600}"), "2:\u{1F600}");
        // A BMP non-ASCII char is 1 UTF-16 unit.
        assert_eq!(field("\u{00E9}"), "1:\u{00E9}"); // e-acute
    }

    #[test]
    fn chain_appends_verifies_and_detects_tamper() {
        let mut chain = EventChain::create(b"runtime-secret", "");
        chain.append("combat.hit", json!({ "target": "goblin", "dmg": 7 }));
        chain.append("xp.award", json!({ "amount": 500 }));
        assert!(chain.verify());
        assert_eq!(chain.size(), 2);

        // Tamper a stored payload - verify must fail.
        let mut tampered: Vec<ChainedRecord> = chain.records().to_vec();
        tampered[0].payload = json!({ "target": "goblin", "dmg": 9 });
        assert!(!EventChain::verify_records(b"runtime-secret", &tampered, ""));

        // Delete the middle (here: the first) record - broken link.
        let truncated: Vec<ChainedRecord> = chain.records()[1..].to_vec();
        assert!(!EventChain::verify_records(b"runtime-secret", &truncated, ""));
    }

    #[test]
    fn seal_round_trips() {
        let mut chain = EventChain::create(b"k", "genesis-seed");
        chain.append("e", json!({ "n": 1 }));
        let seal = chain.seal();
        assert!(EventChain::verify_seal(b"k", &seal));
        assert_eq!(seal.count, 1);
    }
}
