//! Cross-language parity proof for the HMAC event chain.
//!
//! Loads test_vectors/event_chain_v1.json - signatures GENERATED by the real TS
//! EventChain (tools/gen-event-vectors.ts) - and asserts the Rust loom_events
//! crate reproduces every one byte-for-byte. A pass here means the Rust chain is
//! byte-identical to the TS chain: a record signed in one verifies in the other.
//! That is the whole point of the Rust core - one implementation, every surface,
//! provably the same signatures (replay + anti-cheat depend on it).
//!
//! Run: `cargo test -p loom_events --test golden_event_chain`

use loom_events::{hmac_sha256_hex, EventChain};
use serde_json::Value;

const VECTORS: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/../../test_vectors/event_chain_v1.json");

fn load() -> Value {
    let raw = std::fs::read_to_string(VECTORS)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", VECTORS, e));
    serde_json::from_str(&raw).expect("event_chain vectors are not valid JSON")
}

#[test]
fn rust_chain_byte_matches_ts() {
    let v = load();
    let mut failures: Vec<String> = Vec::new();
    let mut passed = 0usize;

    // -- raw HMAC primitive --
    for c in v["hmac"].as_array().expect("missing hmac section") {
        let key = c["key"].as_str().unwrap();
        let message = c["message"].as_str().unwrap();
        let expect = c["expect"].as_str().unwrap();
        let got = hmac_sha256_hex(key.as_bytes(), message);
        if got == expect {
            passed += 1;
        } else {
            failures.push(format!("hmac({:?}, {:?}) = {} != {}", key, message, got, expect));
        }
    }

    // -- full chains: per-record sig, head, and seal --
    for c in v["chains"].as_array().expect("missing chains section") {
        let label = c["label"].as_str().unwrap_or("?");
        let key = c["key"].as_str().unwrap();
        let genesis = c["genesis"].as_str().unwrap();
        let mut chain = EventChain::create(key.as_bytes(), genesis);

        let records = c["records"].as_array().unwrap();
        let expect_sigs = c["expect_sigs"].as_array().unwrap();
        for (i, rec) in records.iter().enumerate() {
            let type_ = rec["type"].as_str().unwrap();
            let payload = rec["payload"].clone();
            let appended = chain.append(type_, payload);
            match appended {
                None => failures.push(format!("[{}] record {} rejected by append", label, i)),
                Some(stored) => {
                    let want = expect_sigs[i].as_str().unwrap();
                    if stored.sig == want {
                        passed += 1;
                    } else {
                        failures.push(format!(
                            "[{}] record {} sig {} != {}",
                            label, i, stored.sig, want
                        ));
                    }
                }
            }
        }

        // head folds in the last sig
        let want_head = c["expect_head"].as_str().unwrap();
        if chain.head() == want_head {
            passed += 1;
        } else {
            failures.push(format!("[{}] head {} != {}", label, chain.head(), want_head));
        }

        // seal commitment (count, head, sig)
        let seal = chain.seal();
        let vseal = &c["seal"];
        let want_count = vseal["count"].as_u64().unwrap();
        let want_seal_head = vseal["head"].as_str().unwrap();
        let want_seal_sig = vseal["sig"].as_str().unwrap();
        if seal.count == want_count && seal.head == want_seal_head && seal.sig == want_seal_sig {
            passed += 1;
            // the chain we just rebuilt must also self-verify
            if !chain.verify() {
                failures.push(format!("[{}] rebuilt chain failed self-verify", label));
            }
        } else {
            failures.push(format!(
                "[{}] seal mismatch: count {}/{} head {}/{} sig {}/{}",
                label, seal.count, want_count, seal.head, want_seal_head, seal.sig, want_seal_sig
            ));
        }
    }

    println!(
        "event-chain golden (Rust): passed={} failed={}",
        passed,
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "Rust loom_events diverges from the TS-generated golden vectors:\n{}",
        failures.join("\n")
    );
}
