"""Cross-language parity: the Python world_snapshot must reproduce the
TS-generated golden vector byte-for-byte (canonical encoding + state hash),
including the strict astral trap. The vector is generated by the real TS
(tools/gen-snapshot-vectors.ts) and also asserted by the Rust harness.
"""

import json
import os
import sys

# Make `loom_engine` importable whether run via pytest or as a plain script.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from loom_engine.world_snapshot import (  # noqa: E402
    canonical_world_state,
    world_state_hash,
    verify_world_snapshot,
    normalize_tags,
)

_VECTOR = os.path.join(
    os.path.dirname(__file__), "..", "..", "test_vectors", "v3_0_snapshot_canonical.json"
)


def test_golden_vector_byte_parity():
    with open(_VECTOR, encoding="utf-8") as f:
        vector = json.load(f)
    cases = vector["cases"]
    assert len(cases) >= 5
    for c in cases:
        label = c["label"]
        assert canonical_world_state(c["input"]) == c["expect_canonical"], "canonical: " + label
        assert world_state_hash(c["key"], c["input"]) == c["expect_hash"], "hash: " + label


def test_verify_and_normalize_tags():
    key = "runtime-secret"
    state = {"epoch": 1, "worldSeed": 2, "entities": {}}
    h = world_state_hash(key, state)
    assert verify_world_snapshot(key, state, h) is True
    assert verify_world_snapshot(key, {"epoch": 1, "worldSeed": 3, "entities": {}}, h) is False
    astral = chr(0x1F40D)  # UTF-16 lead 0xD83D
    bmp = chr(0xF8FF)       # BMP 0xF8FF
    # UTF-16 order: 'a' (0x61) < astral (0xD83D) < bmp (0xF8FF).
    assert normalize_tags([bmp, astral, "a", "a"]) == ["a", astral, bmp]


def test_fail_closed():
    for bad in ({"x": 1.5}, {"x": 9007199254740993}, {"x": -0.0}):
        raised = False
        try:
            world_state_hash("k", bad)
        except ValueError:
            raised = True
        assert raised, "expected ValueError for %r" % (bad,)


def test_rejects_non_nfc():
    # Hardening audit: "e"+U+0301 (NFD) is the same grapheme as U+00E9 (NFC)
    # but a distinct byte string. Reject the non-NFC form as a string VALUE and
    # as an object KEY (mirrors the Rust assert_nfc + TS assertCleanString NFC
    # guard); the precomposed NFC form is accepted. Built from chr() so the
    # source stays pure-ASCII + unambiguous regardless of file normalization.
    import unicodedata as _ud
    base = "cafe" + chr(0x301)
    decomposed = _ud.normalize("NFD", base)
    precomposed = _ud.normalize("NFC", base)
    assert decomposed != precomposed
    for bad in ({"name": decomposed}, {decomposed: 1}):
        raised = False
        try:
            world_state_hash("k", bad)
        except ValueError:
            raised = True
        assert raised, "expected ValueError for non-NFC %r" % (bad,)
    assert isinstance(world_state_hash("k", {"name": precomposed}), str)


if __name__ == "__main__":
    test_golden_vector_byte_parity()
    test_verify_and_normalize_tags()
    test_fail_closed()
    test_rejects_non_nfc()
    print("world_snapshot Python parity: all tests pass")
