"""AST v2 golden-vector harness (Python side) - docs/specs/AST-V2-SPEC.md.

Loads the SHARED test_vectors/ast_v2_families.json (generated by
tools/gen-ast-v2-vectors.ts - the same file the TS harness loads) and runs
every case through the real evaluator with the spec section 1.3 scripted test
PRNG: roll_die pops dice_stream entries in order, roll_die(0) returns 0
WITHOUT popping (mirroring production Pcg32), accept vectors must consume the
stream fully, and reject vectors must reject AT VALIDATION - zero draws, state
unchanged. Assertions follow the section 1.5 normative schema exactly: an
absent expect field is not asserted; entities not listed in any *_after field
are asserted unchanged; `reason` strings are informative only and never
asserted. raw_document vectors (F7) are parsed with this surface's standard
JSON parser (json.loads), so the lexical `3.0` reaches the validator as a
Python float and must accept BY VALUE (spec 1.4).

Also pins the normative spec behaviors a scripted-stream vector cannot
express (throw classes, not resolutions): short-circuit observability (3.2),
the both-operands rule (4.2 step 1), the delta exactness amendment (4.2), the
MAX_WORLD_ENTITIES runtime cap (6.2/8.7), the mutation-structure depth
counter (8.3), and the has_tag `each` static scope rule (4.6).

Run: python python/tests/test_ruleset_ast_v2.py   (or via pytest)
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))

from loom_engine.ruleset_ast import (  # noqa: E402
    apply_triggered_mutations, evaluate_action,
    validate_check, validate_triggered_mutations,
)

_VECTOR = os.path.join(HERE, "..", "..", "test_vectors", "ast_v2_families.json")

PASS = 0
FAIL = 0


def ck(label, cond):
    global PASS, FAIL
    if cond:
        PASS += 1
    else:
        FAIL += 1
        print("  FAIL " + label)


class _ScriptedRng(object):
    """Spec 1.3 scripted test PRNG: entry k is the k-th STREAM-CONSUMING
    roll_die call; zero-sides dice are CALLED but pop nothing; out-of-range
    entries and an exhausted stream are harness failures."""

    def __init__(self, stream, label):
        self.stream = stream
        self.i = 0
        self.label = label

    def roll_die(self, sides):
        if sides == 0:
            return 0
        if self.i >= len(self.stream):
            raise AssertionError(self.label + ": dice stream exhausted (implementation over-draws)")
        v = self.stream[self.i]
        self.i += 1
        if not (1 <= v <= sides):
            raise AssertionError(self.label + ": stream entry %r out of range for d%d" % (v, sides))
        return v


def _ctx(state, actor, target, rng):
    return {"state": state, "actor": actor, "target": target,
            "rng": rng, "natural": None, "each_id": None}


def run_case(v):
    label = v["label"]
    pre = json.dumps(v["state"], sort_keys=True)
    # raw_document vectors (F7): parse THIS string with the surface's standard
    # JSON parser and ignore the ast / mutations fields (spec 1.5).
    if "raw_document" in v:
        doc = json.loads(v["raw_document"])
    elif v["context"] == "check":
        doc = v["ast"]
    else:
        doc = v["mutations"]
    rng = _ScriptedRng(v["dice_stream"], label)
    ctx = _ctx(v["state"], v["actor"], v.get("target"), rng)
    ex = v["expect"]

    if ex.get("reject") is True:
        raised = False
        try:
            if v["context"] == "check":
                evaluate_action(v["state"], doc, ctx)
            else:
                apply_triggered_mutations(v["state"], doc, ctx)
        except Exception:
            raised = True
        ck(label + ": must reject", raised)
        ck(label + ": reject consumes zero PRNG draws", rng.i == 0)
        ck(label + ": reject leaves state unchanged", json.dumps(v["state"], sort_keys=True) == pre)
        return

    if v["context"] == "check":
        r = evaluate_action(v["state"], doc, ctx)
        end_state = r["state"]
        applied = r["mutations"]
        ck(label + ": check-context vectors require expect.degree", "degree" in ex)
        ck(label + ": degree", r["degree"] == ex.get("degree"))
        if "roll" in ex:
            ck(label + ": roll", r["roll"] == ex["roll"])
        if "dc" in ex:
            ck(label + ": dc", r["dc"] == ex["dc"])
        if "delta" in ex:
            ck(label + ": delta", r["delta"] == ex["delta"])
        if "natural" in ex:
            ck(label + ": natural", r["natural"] == ex["natural"])
    else:
        r = apply_triggered_mutations(v["state"], doc, ctx)
        end_state = r["state"]
        applied = r["mutations"]

    # Accept vectors MUST consume the stream fully (this is how the
    # "untaken branches consume zero RNG" pins work - spec 1.3).
    ck(label + ": dice stream fully consumed", rng.i == len(v["dice_stream"]))
    if "rng_draws_total" in ex:
        ck(label + ": rng_draws_total", rng.i == ex["rng_draws_total"])
    ck(label + ": input state never mutated", json.dumps(v["state"], sort_keys=True) == pre)

    listed = {}
    if "props_after" in ex:
        for eid in ex["props_after"]:
            listed[eid] = True
            ent = end_state["entities"].get(eid)
            ck(label + ": props_after " + eid,
               ent is not None and ent["properties"] == ex["props_after"][eid])
    if "tags_after" in ex:
        for eid in ex["tags_after"]:
            listed[eid] = True
            ent = end_state["entities"].get(eid)
            ck(label + ": tags_after " + eid,
               ent is not None and ent["tags"] == ex["tags_after"][eid])
    if "hp_after" in ex:
        for eid in ex["hp_after"]:
            listed[eid] = True
            ent = end_state["entities"].get(eid)
            ck(label + ": hp_after " + eid,
               ent is not None and ent["properties"].get("hp") == ex["hp_after"][eid])
    # Entities NOT listed in any *_after field are asserted UNCHANGED (spec 1.5).
    for eid in v["state"]["entities"]:
        if eid not in listed:
            ck(label + ": entity " + eid + " unchanged",
               end_state["entities"].get(eid) == v["state"]["entities"][eid])
    if "applied" in ex:
        ck(label + ": applied list (exact order)", applied == ex["applied"])
    if "applied_count" in ex:
        ck(label + ": applied_count", len(applied) == ex["applied_count"])


def _raises(fn):
    try:
        fn()
    except Exception:
        return True
    return False


def run_normative_pins():
    MAXI = 9007199254740991

    # 3.2: a decided `and` MUST NOT resolve operands of later children - the
    # missing-target throw in child 2 must never fire once child 1 is false.
    s_and = {"epoch": 0, "worldSeed": 0, "entities": {"a": {"properties": {"hp": 1}, "tags": []}}}
    and_check = {"type": "check", "roll": {"type": "literal", "value": 1}, "dc": {"type": "literal", "value": 0},
                 "degrees": {"success": {"condition": {"type": "and", "conditions": [
                     {"type": "delta_gte", "value": 999},
                     {"type": "compare", "op": "gte",
                      "left": {"source": "prop", "target": "target", "property": "hp"},
                      "right": {"source": "literal", "value": 0}}]},
                     "mutations": []}}}
    r_and = evaluate_action(s_and, and_check, _ctx(s_and, "a", None, _ScriptedRng([], "and-sc")))
    ck("3.2 short-circuited and returns the decided result, no throw", r_and["degree"] == "none")

    # 3.2 (made normative for v1 `or` too): a decided `or` never reaches child 2.
    or_check = {"type": "check", "roll": {"type": "literal", "value": 1}, "dc": {"type": "literal", "value": 0},
                "degrees": {"success": {"condition": {"type": "or", "conditions": [
                    {"type": "delta_gte", "value": 0},
                    {"type": "compare", "op": "gte",
                     "left": {"source": "prop", "target": "target", "property": "hp"},
                     "right": {"source": "literal", "value": 0}}]},
                    "mutations": []}}}
    r_or = evaluate_action(s_and, or_check, _ctx(s_and, "a", None, _ScriptedRng([], "or-sc")))
    ck("3.2 short-circuited or returns the decided result, no throw", r_or["degree"] == "success")

    # 4.2 step 1: BOTH operands are ALWAYS resolved, left then right - a null
    # left (diceless natural) does NOT skip the right operand's missing-target throw.
    both_check = {"type": "check", "roll": {"type": "literal", "value": 1}, "dc": {"type": "literal", "value": 0},
                  "degrees": {"success": {"condition": {"type": "compare", "op": "gte",
                      "left": {"source": "natural"},
                      "right": {"source": "prop", "target": "target", "property": "hp"}},
                      "mutations": []}}}
    ck("4.2 null left operand must still resolve the right operand",
       _raises(lambda: evaluate_action(s_and, both_check, _ctx(s_and, "a", None, _ScriptedRng([], "both")))))

    # 4.2 delta exactness: |roll - dc| > 2^53 - 1 is a RUNTIME error (validation
    # passes - both literals are individually JS-safe).
    delta_check = {"type": "check", "roll": {"type": "literal", "value": MAXI},
                   "dc": {"type": "literal", "value": -MAXI},
                   "degrees": {"success": {"condition": {"type": "delta_gte", "value": 0}, "mutations": []}}}
    ck("4.2 unsafe delta is NOT a validation reject",
       not _raises(lambda: validate_check(delta_check)))
    ck("4.2 unsafe delta throws at runtime",
       _raises(lambda: evaluate_action(s_and, delta_check, _ctx(s_and, "a", None, _ScriptedRng([], "delta")))))

    # 6.2 / 8.7: MAX_WORLD_ENTITIES (65536) is a runtime cap at foreach SELECT -
    # exactly 65536 entities pass, 65537 throw.
    def big_state(n):
        ents = {"foe_one": {"properties": {"hp": 5}, "tags": ["foe"]}}
        for i in range(1, n):
            ents["e%d" % i] = {"properties": {}, "tags": []}
        return {"epoch": 0, "worldSeed": 0, "entities": ents}

    cap_muts = [{"type": "foreach_target", "select": {"tag": "foe"},
                 "mutations": [{"type": "sub_prop", "target": "each", "property": "hp",
                                "value": {"type": "literal", "value": 1}}]}]
    at_cap = big_state(65536)
    ok_run = apply_triggered_mutations(at_cap, cap_muts, _ctx(at_cap, "foe_one", None, _ScriptedRng([], "cap-ok")))
    ck("8.7 65536 entities is within the cap",
       ok_run["state"]["entities"]["foe_one"]["properties"]["hp"] == 4)
    over_cap = big_state(65537)
    ck("8.7 65537 entities throws at SELECT",
       _raises(lambda: apply_triggered_mutations(over_cap, cap_muts,
                                                 _ctx(over_cap, "foe_one", None, _ScriptedRng([], "cap-over")))))

    # 8.3: the mutation-structure depth counter - 16 nested bodies accept,
    # 17 reject at validation.
    def nest_repeats(n):
        inner = []
        for _ in range(n):
            inner = [{"type": "repeat", "count": 1, "mutations": inner}]
        return inner

    ck("8.3 16-deep structure accepts",
       not _raises(lambda: validate_triggered_mutations(nest_repeats(16))))
    ck("8.3 17-deep structure rejects",
       _raises(lambda: validate_triggered_mutations(nest_repeats(17))))

    # 4.6: has_tag with `each` outside any foreach_target body rejects statically.
    ck("4.6 has_tag each outside foreach scope rejects",
       _raises(lambda: validate_triggered_mutations([
           {"type": "if", "condition": {"type": "has_tag", "target": "each", "tag": "x"}, "then": []}])))


def run_vector_file_sanity(vec):
    saw_check = False
    saw_trigger = False
    saw_raw = False
    rejects = 0
    for c in vec["cases"]:
        ck(c["label"] + ": context", c["context"] in ("check", "trigger"))
        ck(c["label"] + ": actor required", isinstance(c.get("actor"), str) and len(c["actor"]) > 0)
        ck(c["label"] + ": dice_stream required", isinstance(c.get("dice_stream"), list))
        if c["context"] == "check":
            saw_check = True
        else:
            saw_trigger = True
        if "raw_document" in c:
            saw_raw = True
            # A canonicalizing reserialization would erase the lexical form
            # under test - the raw text must still carry the non-canonical 3.0.
            ck(c["label"] + ": raw_document keeps the lexical 3.0", "3.0" in c["raw_document"])
            ck(c["label"] + ": raw_document vectors carry no parsed ast", "ast" not in c)
            ck(c["label"] + ": raw_document vectors carry no parsed mutations", "mutations" not in c)
        if c["expect"].get("reject") is True:
            rejects += 1
            # Spec 1.5: all three reject fields are REQUIRED on reject vectors.
            ck(c["label"] + ": reject pins rng_draws_total 0", c["expect"].get("rng_draws_total") == 0)
            ck(c["label"] + ": reject pins state_unchanged", c["expect"].get("state_unchanged") is True)
        elif c["context"] == "check":
            ck(c["label"] + ": accept check vectors require degree", isinstance(c["expect"].get("degree"), str))
    ck("both validation contexts are exercised", saw_check and saw_trigger)
    ck("the raw_document lexical-form vector (F7) is present", saw_raw)
    ck("expected >= 8 reject vectors", rejects >= 8)


def main():
    with open(_VECTOR, encoding="utf-8") as f:
        vec = json.load(f)
    ck("vector file has a cases array", isinstance(vec.get("cases"), list))
    ck("expected >= 38 v2 golden cases", len(vec["cases"]) >= 38)
    for c in vec["cases"]:
        run_case(c)
    run_normative_pins()
    run_vector_file_sanity(vec)
    print("ast_v2 Python parity: passed=%d failed=%d (cases=%d)" % (PASS, FAIL, len(vec["cases"])))


main()


def test_all_module_checks_passed():
    """pytest entry: the ck() checks above run at import; assert none failed.
    (The module-level sys.exit is __main__-guarded so pytest collection of
    the directory does not abort with SystemExit.)"""
    assert FAIL == 0, "%d AST v2 golden check(s) failed - see captured stdout" % FAIL


if __name__ == "__main__":
    sys.exit(1 if FAIL else 0)
