"""SRD 5e action-pack golden-vector harness (Python side).

Loads the SHARED test_vectors/srd5e_pack_v1.json (generated by
tools/gen-srd5e-vectors.ts - the same file the TS harness loads) and runs
every case against the real Python modules:

- kind 'action': the named builder (srd5e_pack) must reproduce the embedded
  ast / mutations document exactly (the builder-drift pin), then the document
  runs through the real AST v2 evaluator (ruleset_ast) with the spec 1.3
  scripted dice stream. Assertions follow the spec 1.5 schema: accept vectors
  consume the stream fully; entities not listed in a *_after field are
  asserted unchanged; the input state is never mutated.
- kinds 'slots' / 'concentration': pure op cases (srd5e_spell_slots /
  srd5e_concentration) compared with deep equality; op inputs must never be
  mutated.

Run: python python/tests/test_srd5e_pack_vectors.py   (or via pytest)
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))

from loom_engine.ruleset_ast import (  # noqa: E402
    apply_triggered_mutations, evaluate_action,
)
from loom_engine.srd5e_pack import (  # noqa: E402
    build_weapon_attack_check, build_attack_cantrip_check, build_save_cantrip_check,
    build_attack_spell_check, build_save_spell_check, build_multi_target_save_trigger,
    build_magic_missile_trigger, build_heal_trigger, build_condition_spell_check,
)
from loom_engine.srd5e_spell_slots import (  # noqa: E402
    spell_slots_for, spend_slot, spend_lowest_available, restore_slot,
    widen_slots, short_rest, long_rest, upcast_effect, total_dice_for_cast,
)
from loom_engine.srd5e_concentration import (  # noqa: E402
    maintain_save_dc, start_concentration, drop_concentration, maintain_save,
)

_VECTOR = os.path.join(HERE, "..", "..", "test_vectors", "srd5e_pack_v1.json")

PASS = 0
FAIL = 0


def ck(label, cond):
    global PASS, FAIL
    if cond:
        PASS += 1
    else:
        FAIL += 1
        print("  FAIL " + label)


class _ScriptedRng(object):
    """Spec 1.3 scripted test PRNG: entry k is the k-th STREAM-CONSUMING
    roll_die call; zero-sides dice are CALLED but pop nothing; out-of-range
    entries and an exhausted stream are harness failures."""

    def __init__(self, stream, label):
        self.stream = stream
        self.i = 0
        self.label = label

    def roll_die(self, sides):
        if sides == 0:
            return 0
        if self.i >= len(self.stream):
            raise AssertionError(self.label + ": dice stream exhausted (implementation over-draws)")
        v = self.stream[self.i]
        self.i += 1
        if not (1 <= v <= sides):
            raise AssertionError(self.label + ": stream entry %r out of range for d%d" % (v, sides))
        return v


def _ctx(state, actor, target, rng):
    return {"state": state, "actor": actor, "target": target,
            "rng": rng, "natural": None, "each_id": None}


def _rebuild(fn, args):
    """The builder dispatch - mirrors the TS harness's rebuild() exactly."""
    if fn == "weapon_attack":
        return build_weapon_attack_check(args[0])
    if fn == "attack_cantrip":
        return build_attack_cantrip_check(args[0], args[1], args[2] if len(args) > 2 else None)
    if fn == "save_cantrip":
        return build_save_cantrip_check(args[0], args[1])
    if fn == "attack_spell":
        return build_attack_spell_check(args[0], args[1])
    if fn == "save_spell":
        return build_save_spell_check(args[0], args[1])
    if fn == "multi_save_trigger":
        return build_multi_target_save_trigger(args[0], args[1], args[2] if len(args) > 2 else None)
    if fn == "magic_missile_trigger":
        return build_magic_missile_trigger(args[0])
    if fn == "heal_trigger":
        return build_heal_trigger(args[0], args[1])
    if fn == "condition_spell":
        return build_condition_spell_check(args[0], args[1])
    raise AssertionError("unknown builder fn: " + str(fn))


def run_action_case(v):
    label = v["label"]
    pre = json.dumps(v["state"], sort_keys=True)
    doc = v["ast"] if v["context"] == "check" else v["mutations"]
    # The builder-drift pin: the named builder must reproduce the embedded
    # document exactly (JSON-normalized deep equality).
    ck(label + ": builder reproduces the embedded document",
       _rebuild(v["build"]["fn"], v["build"]["args"]) == doc)
    rng = _ScriptedRng(v["dice_stream"], label)
    ctx = _ctx(v["state"], v["actor"], v.get("target"), rng)
    ex = v["expect"]
    if v["context"] == "check":
        r = evaluate_action(v["state"], doc, ctx)
        end_state = r["state"]
        applied = r["mutations"]
        ck(label + ": degree", r["degree"] == ex.get("degree"))
        if "roll" in ex:
            ck(label + ": roll", r["roll"] == ex["roll"])
        if "dc" in ex:
            ck(label + ": dc", r["dc"] == ex["dc"])
        if "delta" in ex:
            ck(label + ": delta", r["delta"] == ex["delta"])
        if "natural" in ex:
            ck(label + ": natural", r["natural"] == ex["natural"])
    else:
        r = apply_triggered_mutations(v["state"], doc, ctx)
        end_state = r["state"]
        applied = r["mutations"]
    # Accept vectors MUST consume the stream fully (spec 1.3).
    ck(label + ": dice stream fully consumed", rng.i == len(v["dice_stream"]))
    ck(label + ": input state never mutated", json.dumps(v["state"], sort_keys=True) == pre)
    listed = {}
    if "props_after" in ex:
        for eid in ex["props_after"]:
            listed[eid] = True
            ent = end_state["entities"].get(eid)
            ck(label + ": props_after " + eid,
               ent is not None and ent["properties"] == ex["props_after"][eid])
    if "tags_after" in ex:
        for eid in ex["tags_after"]:
            listed[eid] = True
            ent = end_state["entities"].get(eid)
            ck(label + ": tags_after " + eid,
               ent is not None and ent["tags"] == ex["tags_after"][eid])
    if "hp_after" in ex:
        for eid in ex["hp_after"]:
            listed[eid] = True
            ent = end_state["entities"].get(eid)
            ck(label + ": hp_after " + eid,
               ent is not None and ent["properties"].get("hp") == ex["hp_after"][eid])
    # Entities NOT listed in any *_after field are asserted UNCHANGED (spec 1.5).
    for eid in v["state"]["entities"]:
        if eid not in listed:
            ck(label + ": entity " + eid + " unchanged",
               end_state["entities"].get(eid) == v["state"]["entities"][eid])
    if "applied" in ex:
        ck(label + ": applied list (exact order)", applied == ex["applied"])
    if "applied_count" in ex:
        ck(label + ": applied_count", len(applied) == ex["applied_count"])


def run_op_case(v):
    label = v["label"]
    a = v["args"]
    pre_args = json.dumps(v["args"], sort_keys=True)
    if v["kind"] == "slots":
        if v["op"] == "spell_slots_for":
            got = {"pool": spell_slots_for(a["class"], a["level"])}
        elif v["op"] == "spend":
            sp = spend_slot(a["pool"], a["slot_level"])
            got = {"ok": sp["ok"], "reason": sp["reason"], "slot_level": sp["slot_level"], "pool": sp["slots"]}
        elif v["op"] == "spend_lowest":
            sl = spend_lowest_available(a["pool"], a["min_level"])
            got = {"ok": sl["ok"], "reason": sl["reason"], "slot_level": sl["slot_level"], "pool": sl["slots"]}
        elif v["op"] == "restore":
            got = {"pool": restore_slot(a["pool"], a["slot_level"], a.get("count"))}
        elif v["op"] == "widen":
            got = {"pool": widen_slots(a["stored"], a["class"], a["level"])}
        elif v["op"] == "short_rest":
            got = {"pool": short_rest(a["class"], a["level"], a["pool"])}
        elif v["op"] == "long_rest":
            got = {"pool": long_rest(a["class"], a["level"])}
        elif v["op"] == "upcast":
            got = {"info": upcast_effect(a["spell"], a["cast_level"])}
        elif v["op"] == "total_dice":
            got = {"dice": total_dice_for_cast(a["base"], a["spell"], a["cast_level"])}
        else:
            ck(label + ": unknown slots op " + v["op"], False)
            return
    else:
        if v["op"] == "maintain_dc":
            got = {"dc": maintain_save_dc(a["damage"])}
        elif v["op"] == "start":
            got = start_concentration(a.get("current"), a["spell_id"],
                                      a.get("spell_name"), a.get("slot_level"))
        elif v["op"] == "drop":
            got = drop_concentration(a.get("current"))
        elif v["op"] == "maintain":
            got = maintain_save(a.get("current"), a["damage"], a["con_save_total"])
        else:
            ck(label + ": unknown concentration op " + v["op"], False)
            return
    ck(label + ": op result", got == v["expect"])
    ck(label + ": op inputs never mutated", json.dumps(v["args"], sort_keys=True) == pre_args)


def main():
    with open(_VECTOR, encoding="utf-8") as f:
        vec = json.load(f)
    ck("vector file has a cases array", isinstance(vec.get("cases"), list))
    ck("expected >= 70 golden cases", len(vec["cases"]) >= 70)
    saw_action = False
    saw_slots = False
    saw_conc = False
    for c in vec["cases"]:
        if c["kind"] == "action":
            saw_action = True
            run_action_case(c)
        elif c["kind"] == "slots":
            saw_slots = True
            run_op_case(c)
        elif c["kind"] == "concentration":
            saw_conc = True
            run_op_case(c)
        else:
            ck("unknown case kind: " + str(c.get("kind")), False)
    ck("all three case kinds are exercised", saw_action and saw_slots and saw_conc)
    print("srd5e_pack Python parity: passed=%d failed=%d (cases=%d)" % (PASS, FAIL, len(vec["cases"])))


main()


def test_all_module_checks_passed():
    """pytest entry: the ck() checks above run at import; assert none failed.
    (The module-level sys.exit is __main__-guarded so pytest collection of
    the directory does not abort with SystemExit.)"""
    assert FAIL == 0, "%d srd5e golden check(s) failed - see captured stdout" % FAIL


if __name__ == "__main__":
    sys.exit(1 if FAIL else 0)
