// gen-reconcileFrames-vectors.ts - generate the v5 Phase 2 reconciliation golden vector.
//
// Proves the prediction -> server-correction -> rollback+replay pipeline (Gemini's
// netcode blueprint) is byte-identical across surfaces. The client predicts frames
// 101-102 from frame 100; the server's authoritative frame 101 disagrees (an
// external force moved e1); the client overwrites frame 101 with the server state
// and REPLAYS its unconfirmed frame-102 command via reconcileFrames() to re-derive the
// present. Pins the pre-rollback prediction hash AND the reconciled hash.
// Re-run with: npx tsx tools/gen-reconcileFrames-vectors.ts

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { tickFrame, reconcileFrames, type PlayerCommand, type PlayerEntityMap } from '../src/runtime/world-frame.js';
import { type Ruleset, type WorldAction } from '../src/runtime/world-epoch.js';
import { worldStateHash, type WorldState } from '../src/runtime/world-state-snapshot.js';

var KEY = 'v5-reconcileFrames-golden-key';
var WORLD = 'arena';

// move_right: x += 1 (deterministic, no prng - the reconciliation values stay legible).
var MOVE_RIGHT: WorldAction = { kind: 'mutations', mutations: [{ type: 'add_prop', target: 'self', property: 'x', value: { type: 'literal', value: 1 } }] };
var RULESET: Ruleset = { move_right: MOVE_RIGHT };
var PLAYER_ENTITIES: PlayerEntityMap = { p1: 'e1' };

function cmd(actionId: string): PlayerCommand { return { playerId: 'p1', seq: 1, actionId: actionId }; }

// Frame 100: the last confirmed state. x = 0.
var initial100: WorldState = { frame: 100, epoch: 0, worldSeed: 0, entities: { e1: { properties: { x: 0 }, tags: [] } } } as WorldState;

// CLIENT PREDICTION: apply local move_right at 101 (x=1), then at 102 (x=2).
var predicted101 = tickFrame({ worldId: WORLD, state: initial100, frameNumber: 101, commands: [cmd('move_right')], ruleset: RULESET, playerEntities: PLAYER_ENTITIES });
var predicted102 = tickFrame({ worldId: WORLD, state: predicted101.state, frameNumber: 102, commands: [cmd('move_right')], ruleset: RULESET, playerEntities: PLAYER_ENTITIES });

// SERVER CORRECTION: the authoritative frame-101 state says e1.x = 5 (an external
// force the client could not predict). This is the corrected state at frame 101.
var serverCorrected101: WorldState = { frame: 101, epoch: 0, worldSeed: 0, entities: { e1: { properties: { x: 5 }, tags: [] } } } as WorldState;

// RECONCILE: replay the client's unconfirmed frame-102 command over the corrected
// state -> x = 6.
var commandsByFrame = { '102': [cmd('move_right')] };
var r = reconcileFrames({ worldId: WORLD, correctedState: serverCorrected101, commandsByFrame: commandsByFrame, toFrame: 102, ruleset: RULESET, playerEntities: PLAYER_ENTITIES });

var out = {
  meta: {
    vector: 'v5 Phase 2 - client prediction + rollback reconciliation',
    key: KEY,
    note: 'Generated by the real TS tickFrame + reconcileFrames. Ports load the same inputs and must reproduce: the pre-rollback predicted frame-101 hash (x=1), the predicted frame-102 hash (x=2), and the reconciled frame-102 hash (x=6) after overwriting frame 101 with the server state (x=5) and replaying the unconfirmed frame-102 command. Proves the rollback leaves no trace - the replay re-seeds each frame PRNG from (worldId, frameNumber).',
  },
  inputs: {
    key: KEY,
    worldId: WORLD,
    ruleset: RULESET,
    playerEntities: PLAYER_ENTITIES,
    initial_state: initial100,
    prediction_commands: { '101': [cmd('move_right')], '102': [cmd('move_right')] },
    server_corrected_state: serverCorrected101,
    reconcile_commands_by_frame: commandsByFrame,
    to_frame: 102,
  },
  expect: {
    predicted_101_x: predicted101.state.entities.e1.properties.x,
    predicted_101_hash: worldStateHash(KEY, predicted101.state),
    predicted_102_hash: worldStateHash(KEY, predicted102.state),
    reconciled_102_x: r.state.entities.e1.properties.x,
    reconciled_102_hash: worldStateHash(KEY, r.state),
    frames_replayed: r.framesReplayed,
    reconcile_events_hash: worldStateHash(KEY, r.events),
  },
};

var dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'test_vectors', 'v5_2_reconciliation.json');
writeFileSync(dest, JSON.stringify(out, null, 2) + '\n', 'utf8');
console.log('wrote ' + dest);
console.log('  predicted_101_x=' + out.expect.predicted_101_x + ' reconciled_102_x=' + out.expect.reconciled_102_x + ' frames_replayed=' + out.expect.frames_replayed);
console.log('  reconciled_102_hash=' + out.expect.reconciled_102_hash.slice(0, 16) + '...');
