// Generate the shared cross-language golden vectors for the HMAC event chain.
//
// Runs the REAL engine TS (EventChain + hmacSha256Hex) to compute reference
// signatures, then writes test_vectors/event_chain_v1.json. Both the TS harness
// (tests/golden-event-chain.test.ts) and the Rust harness
// (rust/loom_events/tests/golden_event_chain.rs) load that file and must
// reproduce every signature - so a pass on the Rust side is a real proof that
// the Rust loom_events crate is byte-identical to this TS chain, not merely
// self-consistent.
//
// Re-run after any change to the canonical-message format:
//   npx tsx tools/gen-event-vectors.ts
//
// Payloads are INTEGER-only (the determinism rule bans fractions from signed
// event data) and deliberately exercise the three cross-language traps: object
// key ordering, string escaping, and UTF-16 vs UTF-8 length (astral + BMP chars).

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { EventChain, hmacSha256Hex } from '../src/index.js';
import type { ChainedRecord } from '../src/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'test_vectors', 'event_chain_v1.json');

// --- raw HMAC primitive cases (key + message are plain UTF-8 strings) ---
const hmacCases = [
  // RFC 4231 Test Case 2 - anchors the primitive to a published vector.
  { key: 'Jefe', message: 'what do ya want for nothing?' },
  // A realistic canonical-message-shaped string (length-prefixed framing).
  { key: 'runtime-secret', message: '16:loom.chain.rec/11:13:foo' },
  // Non-ASCII in both key and message (UTF-8 byte path).
  { key: 'kéy-ñ', message: 'mèssage 世界' }, // "世界"
];

interface ChainSpec {
  label: string;
  key: string;
  genesis: string;
  records: Array<{ type: string; payload: unknown }>;
}

const chainSpecs: ChainSpec[] = [
  {
    label: 'mixed payloads, empty genesis',
    key: 'runtime-secret',
    genesis: '',
    records: [
      // Keys intentionally OUT of sorted order -> exercises key-sort canonicalization.
      { type: 'combat.hit', payload: { target: 'goblin', dmg: 7, crit: false } },
      // String with escapes + a nested array + null + negative integer.
      { type: 'log.note', payload: { msg: 'tab\there "quote" \\slash', tags: ['a', 'b'], note: null, delta: -3 } },
      // Nested object + boolean + zero.
      { type: 'xp.award', payload: { amount: 500, source: { kind: 'kill', tier: 0 }, bonus: true } },
    ],
  },
  {
    label: 'world-seed-bound genesis',
    key: 'another-key',
    genesis: 'world:seed:42',
    records: [
      { type: 'currency.debit', payload: { drops: 1, reason: 'mcp.dispatch' } },
      { type: 'currency.debit', payload: { drops: 5, reason: 'turn' } },
    ],
  },
  {
    label: 'unicode payloads (UTF-16 length trap)',
    key: 'k',
    genesis: '',
    records: [
      // BMP non-ASCII (1 UTF-16 unit each) + astral emoji (2 UTF-16 units).
      { type: 'chat', payload: { name: 'Суниса', emote: '\u{1F600}\u{1F525}' } }, // "Суниса", 😀🔥
    ],
  },
];

const chains = chainSpecs.map(function (spec) {
  const chain = EventChain.create({ key: spec.key, genesis: spec.genesis });
  const sigs: string[] = [];
  for (const r of spec.records) {
    const rec = chain.append(r.type, r.payload) as ChainedRecord | null;
    if (rec === null) {
      throw new Error('generator: append rejected a payload it should accept: ' + JSON.stringify(r));
    }
    sigs.push(rec.sig);
  }
  const seal = chain.seal();
  // Sanity: the chain we just built must verify.
  const v = chain.verify();
  if (!v.ok) throw new Error('generator: freshly built chain failed verify: ' + spec.label);
  return {
    label: spec.label,
    key: spec.key,
    genesis: spec.genesis,
    records: spec.records,
    expect_sigs: sigs,
    expect_head: chain.head(),
    seal: { count: seal.count, head: seal.head, sig: seal.sig },
  };
});

const vectors = {
  meta: {
    engine_version: '2.3.0',
    chain_format: 'loom.chain.rec/1',
    note:
      'Cross-language golden vectors for the HMAC-SHA256 event chain. GENERATED by ' +
      'tools/gen-event-vectors.ts from the real engine EventChain. The TS harness ' +
      '(tests/golden-event-chain.test.ts) and the Rust harness ' +
      '(rust/loom_events/tests/golden_event_chain.rs) both reproduce every signature ' +
      '-> proves loom_events (Rust) is byte-identical to the TS chain. Payloads are ' +
      'integer-only (fractions are banned from signed event data).',
  },
  hmac: hmacCases.map(function (c) {
    return { key: c.key, message: c.message, expect: hmacSha256Hex(c.key, c.message) };
  }),
  chains: chains,
};

writeFileSync(outPath, JSON.stringify(vectors, null, 2) + '\n', 'utf8');
// eslint-disable-next-line no-console
console.log('wrote ' + outPath + ' (' + vectors.hmac.length + ' hmac, ' + vectors.chains.length + ' chains)');
