// gen-region-vectors.ts - generate the v5 region-hash golden vector.
//
// Pins the per-region leaf hashes and the global Merkle root for a 3-region world,
// AND the Merkle property: mutating ONE region changes only its leaf + the root,
// leaving the other regions' leaves byte-identical. Ports must reproduce both.
// Also pins the region-sync CLIENT diff over the same leaves: diffRegionLeaves
// (leaves_before vs leaves_after) must report changed=['south'] only.
// Re-run with: npx tsx tools/gen-region-vectors.ts

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { regionLeaves, globalRegionHash } from '../src/runtime/region-hash.js';
import { diffRegionLeaves } from '../src/runtime/region-sync.js';

var KEY = 'v5-region-golden-key';

// A 3-region world. Each region is a world-state-shaped partition (integer props).
var regions: Record<string, unknown> = {
  north: { epoch: 0, worldSeed: 0, entities: { a: { properties: { hp: 10 }, tags: ['orc'] } } },
  south: { epoch: 0, worldSeed: 0, entities: { b: { properties: { hp: 20 }, tags: [] } } },
  east: { epoch: 0, worldSeed: 0, entities: { c: { properties: { hp: 5 }, tags: ['elf'] } } },
};

// Mutate ONLY the south region (b.hp 20 -> 13).
var regionsAfter: Record<string, unknown> = {
  north: { epoch: 0, worldSeed: 0, entities: { a: { properties: { hp: 10 }, tags: ['orc'] } } },
  south: { epoch: 0, worldSeed: 0, entities: { b: { properties: { hp: 13 }, tags: [] } } },
  east: { epoch: 0, worldSeed: 0, entities: { c: { properties: { hp: 5 }, tags: ['elf'] } } },
};

var leavesBefore = regionLeaves(KEY, regions);
var leavesAfter = regionLeaves(KEY, regionsAfter);

var out = {
  meta: {
    generator: 'tools/gen-region-vectors.ts',
    generated_note: 'Regenerate with: npx tsx tools/gen-region-vectors.ts (runs the real TS regionLeaves + globalRegionHash).',
    vector: 'v5 - region hashing (interest-management Merkle)',
    key: KEY,
    note: 'Generated by the real TS regionLeaves + globalRegionHash. Ports load the same regions and must reproduce the per-region leaf hashes and the global root. The "after" mutates only the south region: north/east leaves are byte-identical before/after; only south + the root change (the Merkle property a partial-sync client relies on). diff pins the region-sync client consumer: diffRegionLeaves(leaves_before, leaves_after) must report exactly changed=["south"].',
  },
  inputs: { key: KEY, regions: regions, regions_after_south_mutation: regionsAfter },
  expect: {
    leaves_before: leavesBefore,
    global_before: globalRegionHash(KEY, regions),
    leaves_after: leavesAfter,
    global_after: globalRegionHash(KEY, regionsAfter),
    north_leaf_unchanged: leavesBefore.north === leavesAfter.north,
    east_leaf_unchanged: leavesBefore.east === leavesAfter.east,
    south_leaf_changed: leavesBefore.south !== leavesAfter.south,
    diff: diffRegionLeaves(leavesBefore, leavesAfter),
  },
};

var dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'test_vectors', 'v5_3_region_hash.json');
writeFileSync(dest, JSON.stringify(out, null, 2) + '\n', 'utf8');
console.log('wrote ' + dest);
console.log('  north_unchanged=' + out.expect.north_leaf_unchanged + ' east_unchanged=' + out.expect.east_leaf_unchanged + ' south_changed=' + out.expect.south_leaf_changed);
console.log('  global_before=' + out.expect.global_before.slice(0, 16) + '... global_after=' + out.expect.global_after.slice(0, 16) + '...');
