// gen-ast-vectors.ts - generate the v3.0 ruleset-AST golden vector.
//
// Runs the REAL TS evaluator over a Bleed condition + a 5e attack + a PF2e Strike,
// and pins each case's resolution + resulting state_hash into
// test_vectors/v3_ast_bleed.json. The AST is stored IN the vector, so the Rust +
// Python ports load the SAME AST + assert the SAME outputs (cross-language proof).
// Re-run with: npx tsx tools/gen-ast-vectors.ts

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  applyTriggeredMutations, evaluateAction, makeContext,
  type MutationNode, type CheckNode,
} from '../src/runtime/ruleset-ast.js';
import { worldStateHash, type WorldState } from '../src/runtime/world-state-snapshot.js';

var KEY = 'v3-ast-golden-key';

// Gemini's exact Bleed case: sub hp by floor_div(1d8, 2) on turn start.
var bleedState: WorldState = { epoch: 1, worldSeed: 0, entities: { e1: { properties: { hp: 50 }, tags: [] } } };
var bleedMutations: MutationNode[] = [
  { type: 'sub_prop', target: 'self', property: 'hp',
    value: { type: 'math', op: 'floor_div', left: { type: 'dice', equation: '1d8' }, right: { type: 'literal', value: 2 } } },
];
var bleedSeed = 123456789n;
var bleed = applyTriggeredMutations(bleedState, bleedMutations, makeContext(bleedState, 'e1', bleedSeed));

// 5e attack: 1d20 + str_mod vs AC; crit on nat 20 (2d8), hit on delta>=0 (1d8).
var combat: WorldState = { epoch: 1, worldSeed: 0, entities: {
  hero: { properties: { str_mod: 5 }, tags: [] },
  goblin: { properties: { hp: 20, ac: 12 }, tags: ['foe'] },
} };
var attack5e: CheckNode = {
  type: 'check',
  roll: { type: 'math', op: 'add', left: { type: 'dice', equation: '1d20' }, right: { type: 'prop_ref', target: 'actor', property: 'str_mod' } },
  dc: { type: 'prop_ref', target: 'target', property: 'ac' },
  degrees: {
    critical_success: { condition: { type: 'nat_roll_eq', value: 20 }, mutations: [{ type: 'sub_prop', target: 'target', property: 'hp', value: { type: 'dice', equation: '2d8' } }] },
    success: { condition: { type: 'delta_gte', value: 0 }, mutations: [{ type: 'sub_prop', target: 'target', property: 'hp', value: { type: 'dice', equation: '1d8' } }] },
  },
};
var atk = evaluateAction(combat, attack5e, makeContext(combat, 'hero', 777n, 'goblin'));

// PF2e Strike: crit on (delta>=10 OR nat 20) -> 2x damage; hit on delta>=0.
var strikePf2e: CheckNode = {
  type: 'check',
  roll: { type: 'math', op: 'add', left: { type: 'dice', equation: '1d20' }, right: { type: 'prop_ref', target: 'actor', property: 'str_mod' } },
  dc: { type: 'prop_ref', target: 'target', property: 'ac' },
  degrees: {
    critical_success: { condition: { type: 'or', conditions: [{ type: 'delta_gte', value: 10 }, { type: 'nat_roll_eq', value: 20 }] },
      mutations: [{ type: 'sub_prop', target: 'target', property: 'hp', value: { type: 'math', op: 'mul', left: { type: 'dice', equation: '1d8' }, right: { type: 'literal', value: 2 } } }] },
    success: { condition: { type: 'delta_gte', value: 0 }, mutations: [{ type: 'sub_prop', target: 'target', property: 'hp', value: { type: 'dice', equation: '1d8' } }] },
  },
};
var strike = evaluateAction(combat, strikePf2e, makeContext(combat, 'hero', 4242n, 'goblin'));

var out = {
  meta: {
    vector: 'v3.0 ruleset-AST resolution',
    key: KEY,
    note: 'Generated by the real TS evaluator. Rust + Python ports load the same AST + assert the same outputs (incl floor_div, nat_roll_eq, the degree order, and the resulting world-state hash).',
  },
  cases: [
    { label: 'Bleed: sub_prop hp by floor_div(1d8,2) on_turn_start', kind: 'condition', key: KEY, seed: bleedSeed.toString(), actor: 'e1',
      state: bleedState, mutations: bleedMutations,
      expect: { hp_after: bleed.state.entities.e1.properties.hp, applied: bleed.mutations, state_hash: worldStateHash(KEY, bleed.state) } },
    { label: '5e attack: 1d20+str vs AC (seed 777)', kind: 'action', key: KEY, seed: '777', actor: 'hero', target: 'goblin',
      state: combat, check: attack5e,
      expect: { degree: atk.degree, roll: atk.roll, natural: atk.natural, dc: atk.dc, delta: atk.delta, hp_after: atk.state.entities.goblin.properties.hp, state_hash: worldStateHash(KEY, atk.state) } },
    { label: 'PF2e Strike: 4 degrees (seed 4242)', kind: 'action', key: KEY, seed: '4242', actor: 'hero', target: 'goblin',
      state: combat, check: strikePf2e,
      expect: { degree: strike.degree, roll: strike.roll, natural: strike.natural, dc: strike.dc, delta: strike.delta, hp_after: strike.state.entities.goblin.properties.hp, state_hash: worldStateHash(KEY, strike.state) } },
  ],
};

var dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'test_vectors', 'v3_ast_bleed.json');
writeFileSync(dest, JSON.stringify(out, null, 2) + '\n', 'utf8');
console.log('wrote ' + dest);
for (var i = 0; i < out.cases.length; i++) {
  var c = out.cases[i];
  console.log('  ' + c.label + ' -> ' + JSON.stringify(c.expect).slice(0, 110));
}
