// gen-session-vectors.ts - generate the v3.0 Phase 4 WorldSession golden vector.
//
// Builds a REAL bundle: tickEpoch produces an EpochResolved event, it is signed
// into an HMAC EventChain, and suspend() packs {snapshot @ epoch 5, chainTail =
// [that event], tailGenesis}. Then resume() verifies the snapshot, verifies +
// replays the chain tail via the recorded-mutation reducer (epoch 5 -> 6), and
// catches up offline epochs 7..8 (currentEpoch 9, maxCatchup 2, so 1 epoch is
// voided). The resulting hashes are pinned so the Python / Rust / WASM / PyO3 ports
// reproduce the entire suspend/resume pipeline byte-for-byte.
// Re-run with: npx tsx tools/gen-session-vectors.ts

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { EventChain } from '../src/runtime/event-chain.js';
import { tickEpoch, type Ruleset, type WorldAction } from '../src/runtime/world-epoch.js';
import { suspend, resume, replayEpochEvent } from '../src/runtime/world-session.js';
import { worldStateHash, type WorldState } from '../src/runtime/world-state-snapshot.js';

var KEY = 'v3-session-golden-key';
var WORLD = 'persephone';
var GENESIS = 'loom.world/persephone';
var TAG = 'faction';

var GAIN: WorldAction = { kind: 'mutations', mutations: [{ type: 'add_prop', target: 'self', property: 'power', value: { type: 'dice', equation: '1d6' } }] };
var REST: WorldAction = { kind: 'mutations', mutations: [{ type: 'add_prop', target: 'self', property: 'power', value: { type: 'literal', value: 1 } }] };
var RULESET: Ruleset = { gain_power: GAIN, rest: REST };

// Snapshot state S0 at epoch 5.
var S0: WorldState = { epoch: 5, worldSeed: 0, entities: { faction_1: { properties: { power: 10 }, tags: [TAG] } } };

// E1: tickEpoch resolves epoch 6 over S0 (this is what was written to the chain
// AFTER the snapshot but before suspend - the "tail").
var t1 = tickEpoch({ worldId: WORLD, state: S0, epochNumber: 6, proposals: { faction_1: { actionId: 'gain_power' } }, ruleset: RULESET, actorTags: [TAG] });

// Sign E1 into an HMAC chain, then suspend at snapshot index 0 (tail = [E1]).
var chain = EventChain.create<typeof t1.event>({ key: KEY, genesis: GENESIS });
chain.append('EpochResolved', t1.event);
var bundle = suspend({ key: KEY, worldId: WORLD, snapshotState: S0, snapshotEventIndex: 0, chain: chain });

// Resume: clock is at epoch 9, but maxCatchup 2 caps the world at epoch 8 (1 voided).
var proposalsByEpoch = { '7': { faction_1: { actionId: 'rest' } }, '8': { faction_1: { actionId: 'gain_power' } } };
var r = resume({ key: KEY, bundle: bundle, currentEpoch: 9, ruleset: RULESET, proposalsByEpoch: proposalsByEpoch, maxCatchup: 2, actorTags: [TAG] });

// The state after the tail replay (before catch-up) MUST equal tickEpoch's own S1
// (the reducer reconstructs what the event recorded).
var afterTail = replayEpochEvent(S0, t1.event);

var out = {
  meta: {
    generator: 'tools/gen-session-vectors.ts',
    generated_note: 'Regenerate with: npx tsx tools/gen-session-vectors.ts (runs the real TS suspend/resume).',
    vector: 'v3.0 Phase 4 - WorldSession suspend/resume',
    key: KEY,
    note: 'Generated by the real TS suspend/resume. BUNDLE FORMAT v2: the bundle carries a structural ChainSeal (seal field) which TS resume() verifies fail-closed against the tail; ports that have not grown the check yet ignore the extra field. Ports load the bundle, verify the snapshot hash + the HMAC chain tail, replay the tail via the recorded-mutation reducer (NOT the AST), then run bounded catch-up, and must reproduce intermediate_state_hash_post_tail, final_state_hash, newEvents_hash, and the counts. tail_reducer_equals_tick proves the reducer reconstructs tickEpoch output.',
  },
  inputs: {
    key: KEY,
    worldId: WORLD,
    bundle: bundle,
    currentEpoch: 9,
    maxCatchup: 2,
    ruleset: RULESET,
    proposalsByEpoch: proposalsByEpoch,
    actorTags: [TAG],
  },
  expect: {
    intermediate_state_hash_post_tail: worldStateHash(KEY, afterTail),
    tail_reducer_equals_tick: worldStateHash(KEY, afterTail) === worldStateHash(KEY, t1.state),
    final_epoch: r.state.epoch,
    epochsResolved: r.epochsResolved,
    epochsVoided: r.epochsVoided,
    newEvents_count: r.newEvents.length,
    newEvents_hash: worldStateHash(KEY, r.newEvents),
    final_state_hash: worldStateHash(KEY, r.state),
  },
};

var dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'test_vectors', 'v3_4_world_session.json');
writeFileSync(dest, JSON.stringify(out, null, 2) + '\n', 'utf8');
console.log('wrote ' + dest);
console.log('  tail_reducer_equals_tick=' + out.expect.tail_reducer_equals_tick
  + ' final_epoch=' + out.expect.final_epoch
  + ' resolved=' + out.expect.epochsResolved + ' voided=' + out.expect.epochsVoided
  + ' newEvents=' + out.expect.newEvents_count);
console.log('  final_state_hash=' + out.expect.final_state_hash.slice(0, 16) + '...');
