// gen-frame-vectors.ts - generate the v5 Phase 1 command-frame golden vector.
//
// Runs the REAL TS tickFrame over: a 2-player frame (commands sorted by numeric-
// aware playerId then seq), an unknown-player rejection, a per-player rate cap, and
// a check-action command - pinning the resulting world-state hash + the FrameResolved
// event hash so the Rust / WASM / PyO3 / C-ABI ports reproduce the server-authoritative
// frame byte-for-byte. Re-run with: npx tsx tools/gen-frame-vectors.ts

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { tickFrame, type PlayerCommand, type PlayerEntityMap } from '../src/runtime/world-frame.js';
import { type Ruleset, type WorldAction } from '../src/runtime/world-epoch.js';
import { worldStateHash, type WorldState } from '../src/runtime/world-state-snapshot.js';

var KEY = 'v5-frame-golden-key';

var MOVE: WorldAction = { kind: 'mutations', mutations: [{ type: 'add_prop', target: 'self', property: 'x', value: { type: 'dice', equation: '1d4' } }] };
var STRIKE: WorldAction = {
  kind: 'check',
  check: {
    type: 'check',
    roll: { type: 'dice', equation: '1d20' },
    dc: { type: 'literal', value: 10 },
    degrees: {
      success: { condition: { type: 'delta_gte', value: 0 }, mutations: [{ type: 'sub_prop', target: 'target', property: 'hp', value: { type: 'literal', value: 5 } }] },
      failure: { condition: { type: 'delta_lte', value: -1 }, mutations: [] },
    },
  },
};
var RULESET: Ruleset = { move: MOVE, strike: STRIKE };

interface Case {
  label: string;
  key: string;
  worldId: string;
  state: WorldState;
  frameNumber: number;
  commands: PlayerCommand[];
  playerEntities: PlayerEntityMap;
  ruleset: Ruleset;
  maxCommandsPerPlayer?: number;
  maxCommands?: number;
  expect: Record<string, unknown>;
}
var cases: Case[] = [];

function frameCase(label: string, worldId: string, state: WorldState, frameNumber: number,
  commands: PlayerCommand[], playerEntities: PlayerEntityMap,
  maxCommandsPerPlayer: number | undefined, maxCommands: number | undefined): void {
  var r = tickFrame({ worldId, state, frameNumber, commands, ruleset: RULESET, playerEntities, maxCommandsPerPlayer, maxCommands });
  var listed: string[] = [];
  for (var i = 0; i < r.event.commands_processed.length; i++) {
    listed.push((r.event.commands_processed[i] as { player_id: string }).player_id);
  }
  cases.push({
    label, key: KEY, worldId, state, frameNumber, commands, playerEntities, ruleset: RULESET, maxCommandsPerPlayer, maxCommands,
    expect: {
      listed_players: listed,
      pcg_steps_consumed: r.event.pcg_steps_consumed,
      resolved: r.resolved,
      rejected: r.rejected,
      event: r.event,
      event_hash: worldStateHash(KEY, [r.event]),
      state_hash: worldStateHash(KEY, r.state),
    },
  });
}

// 1. Two players, numeric-aware order: p2 before p10, each moves (1d4).
frameCase('two-player frame: p2 before p10 by numeric-aware id', 'arena', {
  frame: 0, epoch: 0, worldSeed: 0, entities: {
    e2: { properties: { x: 0 }, tags: [] },
    e10: { properties: { x: 0 }, tags: [] },
  },
} as WorldState, 1,
  [{ playerId: 'p10', seq: 1, actionId: 'move' }, { playerId: 'p2', seq: 1, actionId: 'move' }],
  { p2: 'e2', p10: 'e10' }, undefined, undefined);

// 2. Per-player seq ordering + a SECOND command from one player, with a per-player
//    cap of 1 -> the second command is rate_limited.
frameCase('per-player seq order + rate cap (maxPerPlayer=1)', 'arena', {
  frame: 0, epoch: 0, worldSeed: 0, entities: { e1: { properties: { x: 0 }, tags: [] } },
} as WorldState, 1,
  [{ playerId: 'p1', seq: 2, actionId: 'move' }, { playerId: 'p1', seq: 1, actionId: 'move' }],
  { p1: 'e1' }, 1, undefined);

// 3. Unknown player (controls no entity) -> rejected, zero prng; the valid player
//    still resolves unshifted.
frameCase('unknown-player command rejected (zero prng, others unshifted)', 'arena', {
  frame: 0, epoch: 0, worldSeed: 0, entities: { e1: { properties: { x: 0 }, tags: [] } },
} as WorldState, 1,
  [{ playerId: 'ghost', seq: 1, actionId: 'move' }, { playerId: 'p1', seq: 1, actionId: 'move' }],
  { p1: 'e1' }, undefined, undefined);

// 4. Check-action command (Strike vs a target) - exercises the evaluateAction path.
frameCase('check-action command: strike resolves a degree', 'arena', {
  frame: 0, epoch: 0, worldSeed: 0, entities: {
    hero: { properties: {}, tags: [] },
    goblin: { properties: { hp: 20 }, tags: [] },
  },
} as WorldState, 7,
  [{ playerId: 'p1', seq: 1, actionId: 'strike', targetId: 'goblin' }],
  { p1: 'hero' }, undefined, undefined);

var out = {
  meta: {
    vector: 'v5.0 Phase 1 - deterministic command-frame tick',
    key: KEY,
    note: 'Generated by the real TS tickFrame. Ports load the same inputs and must reproduce the listed players, pcg_steps_consumed, resolved/rejected counts, the FrameResolved event, and the resulting world-state + event hashes. Pins the (compareIds(playerId), seq) command order, the per-player rate cap, the unknown-player rejection (zero prng), and the check-action path.',
  },
  cases,
};
var dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'test_vectors', 'v5_1_command_frame.json');
writeFileSync(dest, JSON.stringify(out, null, 2) + '\n', 'utf8');
console.log('wrote ' + dest + ' (' + cases.length + ' cases)');
for (var i = 0; i < cases.length; i++) {
  console.log('  ' + cases[i].label + ' -> resolved=' + cases[i].expect.resolved + ' rejected=' + cases[i].expect.rejected + ' state ' + String(cases[i].expect.state_hash).slice(0, 12) + '...');
}
